### ISSUE TITLE
`find_by` is not implemented on Rails 3.2

### ISSUE THREAD

**Issue by aortbals** [magnusvk/counter_culture#100]
[This commit](https://github.com/magnusvk/counter_culture/commit/56d347a9bbcb3115e40d5befaca23fd5650c6ceb) breaks support for Rails 3.2 because `find_by` was [not implemented in Rails 3.2](http://api.rubyonrails.org/v3.2.16/). While the change is nice, I believe it is the only reason I'm prevented from using the latest version (`0.1.31` currently) on Rails 3.2.16.

**Comment by magnusvk** [comment]
That's fair enough; yeah, the change is nice but it's not worth breaking compatibility. I've reverted that commit, and version 0.1.32 should work for you again.

**Comment by magnusvk** [comment]
Also, issue #100. Woot, woot! :)

**Comment by aortbals** [comment]
Appreciate it!
