### ISSUE TITLE
default_scope of association

### ISSUE THREAD

**Issue by sebfie** [magnusvk/counter_culture#102]
Hello,

I have a model product : 

````
class Product < ActiveRecord::Base
  has_many :store_products, dependent: :destroy
end
````

and store product : 

````
class StoreProduct < ActiveRecord::Base
  belongs_to :product, :class_name => 'Product', :foreign_key => :product_id
  counter_culture :product
  default_scope where(:disabled => false)
end
````

And my counter_culture counter do not takes care about this default scope. How to fix that?

**Comment by magnusvk** [comment]
You could do something similar to [this](https://github.com/magnusvk/counter_culture/blob/master/lib/counter_culture.rb#L99) if you can turn the default scope into a SQL `WHERE` somehow. Personally, though, I'd recommend against using `default_scope`. It's caused nothing but pain for me when I have.
