### ISSUE TITLE
Fixing counts on belongs_to with joins not supported

### ISSUE THREAD

**Issue by mrj** [magnusvk/counter_culture#106]
[requires further thought]

**Comment by magnusvk** [comment]
Hm, weird that your comment is gone here. Did you edit it?

As to your question: I don't know exactly what you mean by "belongs_to with joins". Could you give me an example with some code of what that actually looks like? Happy to look at that then; closing in the meantime.

**Comment by mrj** [comment]
Yes sorry, I deleted my comment while I implemented a manual `counter_culture_fix_counts` to clarify my thinking. I've restored the comment.

The problem is real, but I'm not sure whether it's obscure enough to forgo automatic support.

It's where a `belongs_to` is defined like
````
belongs_to :relation, proc { joins(...) }...
`````
which I'm using to link to an aggregate record not fully determined by the foreign key (perhaps an abuse of `belongs_to`, but it neatly does the job). There's no `belongs_to` chain here of the form that counter_culture supports.

While counter_culture works with such a relation when updating the counts after a record is modified, fix counts fails because of the missing joins. Everything should work if a counter_culture declaration had a `:joins` option which gets injected into the fix counts SQL.

**Comment by magnusvk** [comment]
Yeah, I think that's obscure enough that adding general support for this case probably doesn't make sense. But you should still be able to use the gem for actually maintaining counters and just write a more naive and less performant version of fix_counts that uses the relation directly.

**Comment by mrj** [comment]
Yes, that's what I've done.

Implementing the manual counter_culture_fix_counts made it clear that the extra joins needed to fix the counts are different from the extra ones in relation. Plus a counter_culture `:joins` option would have to support this parameter being a proc/lambda that took the record as an argument.
