### ISSUE TITLE
How to fix counts only one record

### ISSUE THREAD

**Issue by JNajera** [magnusvk/counter_culture#108]
Im updating my records with update_all to get the best performance because its a large set of records, so this don't call any callbacks and the counter its not updated. But when I done the update, Im actually fixing the counter manually with this command: 
```
List. counter_culture_fix_counts :only => :list_customers 
```
This will fix the counter for all the records. Its possible to call it for just one record? 
Thanks

**Comment by magnusvk** [comment]
You cannot use fix_counts for that, no. But you can just do an update_columns on the counter cache column with the correct count you grab from the actual association. The only reason to use fix_counts is because it is fast and works in bulk.
