### ISSUE TITLE
Scoped Count

### ISSUE THREAD

**Issue by maxsalven** [magnusvk/counter_culture#109]
Using a similar example to the ReadMe:

```ruby
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  counter_culture [:product, :category]
end

class Product < ActiveRecord::Base
  has_many :reviews
  belongs_to :category
end

class Category < ActiveRecord::Base
  has_many :products
end
```

I'd like a counter_cache on Category (`user_reviews_count`) that tells me how many *different* users have reviewed products in that category. So not the total number of reviews (which is what the above would do), but the number of users that have created a review.

**Comment by magnusvk** [comment]
That makes sense; unfortunately, counter_culture doesn't support that scenario right now and I don't have any plans of adding that functionality. I would be very willing to merge a pull request that adds it, though. You could look at the `delta_column` support as a template for how to go about that.
