### ISSUE TITLE
Counter Culture getting incorrect count with after_create hook

### ISSUE THREAD

**Issue by danahern** [magnusvk/counter_culture#11]
We are having a problem with our implementation of counter cache.  When we have an after_create method it ends up doubling up the count (returning 2 instead of 1).

Here is a simple setup

```
class Issue < ActiveRecord::Base
  belongs_to :order
  counter_culture :order
  after_create :set_ticket_number
  def set_ticket_number
    update_attribute(:ticket_number, 200000+id)
  end
end

class Order < ActiveRecord::Base
  has_many :issues
end
```

Then in the console

```
>> o = Order.first
=> #<Order id: 1, issues_count: 0>
>> o.issues_count
=> 0
>> o.issues
=> []
>> o.issues.create
   (0.1ms)  BEGIN
  SQL (0.5ms)  INSERT INTO `issues` (`order_id`, `ticket_number`) VALUES (1, NULL)
  Order Load (0.7ms)  SELECT `orders`.* FROM `orders` WHERE `orders`.`id` = 1 LIMIT 1
   (0.3ms)  UPDATE `issues` SET `order_id` = 1, `ticket_number` = 1217251 WHERE `issues`.`id` = 1017251
   (0.7ms)  COMMIT
  SQL (0.6ms)  UPDATE `orders` SET `issues_count` = COALESCE(`issues_count`, 0) + 1 WHERE `orders`.`id` = 1
  SQL (0.5ms)  UPDATE `orders` SET `issues_count` = COALESCE(`issues_count`, 0) + 1 WHERE `orders`.`id` = 1
=> #<Issue id: 1017251, order_id: 1, ticket_number: 1217251>
>> o.issues.size
=> 1
>> o.reload
  Order Load (0.4ms)  SELECT `orders`.* FROM `orders` WHERE `orders`.`id` = 1 LIMIT 1
=> #<Order id: 1, issues_count: 2>
>> o.issues_count
=> 2

```

Switching back to the Rails counter_cache: true fixes it, also commenting out the after_create fixes it.  

Do you have any ideas why it might be doing that?  I took a look at the source shortly and thought I might have been interfering with your after_create hook.

Thanks for the awesome gem, it's stopped a lot of our dead lock issues.

**Comment by andela-atemitope** [comment]
Hey Magnusk, perhaps I can get some clarity on the issue i'm currently facing with counter culture gem. I've got a rails 4.2.4 url_shortening application which consists of both my user and link models. I am trying to use counter caching to ensure i can get a list of users sorted according the amount of links they have. After including counter_culture in my gem file, ran bundle and used its generator... i added <counter_culture :user>   to my link model  i keep getting this error in  my server  <UPDATE "users" SET "links_count" = COALESCE("links_count", 0) + 1 WHERE "users"."id" = ?  [["id", 6]]
SQLite3::SQLException: no such column: links_count: UPDATE "users" SET "links_count" = COALESCE("links_count", 0) + 1 WHERE "users"."id" = ?
Error in execute_after_commit block: #<ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: links_count: UPDATE "users" SET "links_count" = COALESCE("links_count", 0) + 1 WHERE "users"."id" = ?>
Completed 500 Internal Server Error in 1131ms (ActiveRecord: 369.5ms)

ActiveRecord::StatementInvalid (SQLite3::SQLException: no such column: links_count: UPDATE "users" SET "links_count" = COALESCE("links_count", 0) + 1 WHERE "users"."id" = ?):>
