### ISSUE TITLE
Is it possible to have two has_many :through relations?

### ISSUE THREAD

**Issue by misham** [magnusvk/counter_culture#110]
I have a data model as follows:

```ruby
class Story < ActiveRecord::Base
  has_many :task_story_lists
  has_many :tasks, :through :task_story_lists
end

class Task < ActiveRecord::Base
  belongs_to :stage

  has_many :task_story_lists
  has_many :stories, :through => :task_story_lists 
end

class Stage < ActiveRecord::Base
   has_many :tasks

   has_many :stage_goals
   has_many :goals, :through => :stage_goals
end

class Goal < ActiveRecord::Base
  has_many :stage_goals
  has_many :stages, :through => :stage_goals
end
```

I'd like to have a counter cache of `Stories` on `Stages`.  I know that there will be duplicates, that's allowed per business rules.

I ran the migration to add `stories_counter` to `Goal` model.  I also tried adding a `counter_culture` line to `TaskStoryList` as follows:

```ruby
counter_culture [:task, :stage, :goals], :column_name => 'stories_counter`
```

but that doesn't create the counts.

Is this even possible?  Do you I need to have some kind of "intermediary" counter or a custom counter?

Thank you

**Comment by magnusvk** [comment]
Have you tried `counter_culture [:task, :stage, :stage_goals, :stage]` instead?
