### ISSUE TITLE
Counter culture works on delegated attributes, but not when updated

### ISSUE THREAD

**Issue by chamini2** [magnusvk/counter_culture#112]
I have the following class

    class Submission < ActiveRecord::Base
      # always include the associated task in the queries
      default_scope { includes(:task) }

      belongs_to :owner, class_name: 'Profile'
      belongs_to :task

      # keep the sum of points of accepted submissions in the owner's model
      counter_culture :owner, delta_column: 'points', column_name: Proc.new { |sub| sub.accepted? ? 'points' : nil }
      delegate :points, to: :task
    end

And when creating Submissions, they correctly add in the `Profile` model; but when updating `points` in the `Task` model, these changes do not reflect on `Profile` through `Submission`.

Is there a method I can call in `Task` to make `Submission` now of the change, updating `Profile`?

**Comment by magnusvk** [comment]
Is there a reason you can't define this directly on `Task` using a multi-level counter cache? I think that would work.
