### ISSUE TITLE
Is it possible to define a custom aggregation function instead of COUNT or SUM?

### ISSUE THREAD

**Issue by ProGM** [magnusvk/counter_culture#115]
In my use case, I'd like to cache the mean rating of some votes.

Example:

```ruby
class Product < ActiveRecord::Base
  has_many :votes
end
```

```ruby
class Vote < ActiveRecord::Base
   belongs_to :product
  counter_culture :product, column_name: 'rating', delta_column: 'score', using: 'avg(*)'
end
```

Is there a way to do it using counter_culture?

Otherwise, can I try to add this feature? :)

**Comment by magnusvk** [comment]
There's no way to do this currently. I'd be happy to look at a pull request that adds this functionality. However, I don't think there's a super straightforward way of doing this. You may be thinking only about `counter_culture_fix_counts` where this would be fairly easy to add, I think. But remember that counter_culture also increments / decrements the count using the delta column. If we supported something like an average, it would have to redo the entire average, right? It can't just adjust it based on the one `delta_column` value. So you may want to do this differently?

But all this being said, if you come up with a good way to do this in counter_culture I'm happy to merge that. :)
