### ISSUE TITLE
previous_model setters fail when writer method is not defined / raises exception

### ISSUE THREAD

**Issue by melcher** [magnusvk/counter_culture#116]
We ran into an issue that prevents us from using counter_culture.
A model that does not define a setter method for a database attribute will raise an exception when using counter_culture. We find this a useful pattern for fields that store the side effect of another action but should not be updated directly. See this example activerecord class:
```ruby
create_table :users do |t|
  t.string :first_name
  t.string :last_name
  t.string :name
end

class User < ActiveRecord::Base
  def name=(new_name)
    fail "Do not set name directly, instead set first_name or last_name"
  end
  def first_name=(*args)
    super
    write_attribute(:name, "#{first_name} #{last_name}")
  end
  def last_name=(*args)
    super
    write_attribute(:name, "#{first_name} #{last_name}")
  end
end
```

Using counter_culter with this class will fail when it iterates through changed_attributes and creates a copy by assigning each attribute. Do you plan to support any other options here? Using write_attribute, for example, would work in our case. Or disabling this when it's not used?

The code that iterates through each attribute and sets them using writer methods is at:
lib/counter_culture.rb:355

Thanks,
- Graham

**Comment by magnusvk** [comment]
Graham -- yes, that'd be a change I'd be happy to merge. Can you put together a pull request? Thanks!

**Comment by magnusvk** [comment]
Graham -- wanted to follow up here and see if you can put together a pull request for this? Thanks.

**Comment by melcher** [comment]
Hey there,
We ended up not needing this plugin and just went with the default rails counter's for our app. If we end up needing this in the future I may be able to dedicate some time to come up with a patch but not currently a need for us. Closing the issue since there doesn't seem to be much of a need outside of our use case.
