### ISSUE TITLE
Must provide :column_names option for relation when column name is a proc

### ISSUE THREAD

**Issue by almnes** [magnusvk/counter_culture#118]
Seem to be running into some issues, I've set up my counter culture like this:
    
    class User < ActiveRecord::Base
    belongs_to :company
    counter_culture :company, :column_name => Proc.new { |user| user.active? ? 'users_count' : nil }

and I have my `users_count` setup on `Company` with a migration like this:

     add_column :companies, :users_count, :integer, default: 0, null: false

now when I try to run `User.counter_culture_fix_counts` I get a RunTimeError stating:

`RuntimeError: Must provide :column_names option for relation [:company] when :column_name is a Proc; you may skip this relation with :skip_unsupported => true`

now it seems like I already have setup what it requires.

**Comment by magnusvk** [comment]
Well, you need to do exactly what the error message says you have to do. You have the `:column_name` set to the `Proc`. This will enable normal counter cache behavior. However, for `fix_counts` to work you also need to add the `:column_names` option [as documented in the README](https://github.com/magnusvk/counter_culture#handling-dynamic-column-names).
