### ISSUE TITLE
Move counter cache update back into transaction

### ISSUE THREAD

**Issue by magnusvk** [magnusvk/counter_culture#120]
Currently, the counter cache update happens outside of the transaction in the after_commit hook. This is to avoid a historical deadlock issue in Postgres. However, this should be fixed in Postgres 9.3, [according to this](http://mina.naguib.ca/blog/2010/11/22/postgresql-foreign-key-deadlocks.html) and the release notes. 

Given that, it should be optional in counter_culture whether the update should happen in or outside of the transaction. It should default to inside the transaction.

**Comment by magnusvk** [comment]
cc @DavidMikeSimon

**Comment by c0m3tx** [comment]
Hi all, any news about this?

**Comment by magnusvk** [comment]
No news, no. Feel free to work on it though! 😄 I've never worked with the test_after_commit gem, so no ideas there. How are you trying to use it?

**Comment by magnusvk** [comment]
I think it's even simpler than that. It'd just need a method that conditionally yields directly or calls `execute_after_commit`.

**Comment by kulte** [comment]
@magnusvk Check out #145. Let me know if you'd like me to add any specs, but I'm not really sure how to reliably test what happened inside and outside of an ActiveRecord transaction.

**Comment by magnusvk** [comment]
This is no longer the case in the just-released version 1.0.0. Thank you @kulte for the pull request.

**Comment by jbritten** [comment]
I'm experiencing deadlocks using MySQL & counter_cache at scale (database under heavy load with many concurrent requests competing to update the counters).

Any chance the "execute_after_commit" option can be added back? I don't understand why it was removed from 2.x in the first place. Seems that whether to update the counters inside or outside of the transaction should be left to the user to decide, right?

I cannot revert to the 1.x branch because I need other improvements in the 2.x branch (i.e. bug fixes for discard integration).

**Comment by magnusvk** [comment]
Sorry you're having issues with this. Interestingly, this issue was first added because of deadlock issues with Postgres. It's somewhat ironic that it's now MySQL causing a similar issue.

In any case, the history of removing this comes from a bugfix to allow multiple saves in one transaction, see 81dfbf55495b59afab844bbd0ff14fbff3cb922b. Plus, in the absence of issues like this with the database layer, I don't see why you'd ever want to push the counter cache update outside of the transaction. But then again, you _are_ seeing database issues.

To address your immediate issue, you could probably run a fork of current master with 7639b08569851ebafda1f6f3dceccf0dcab15bda reverted relatively easily. Now that's not a great long-term solution, obviously, but just throwing that out there.

If you can figure out how to write a test for this behavior, I think I'd probably be down to re-add this functionality, given that the original code for this was quite straightforward.

This is the first I'm hearing of this issue, so not sure how widespread it is, but of course still would be good to figure out how to address this for you. @jbritten

**Comment by jbritten** [comment]
Thank you for summarizing the history of this change and work-around suggestions. Ironically, I received another deadlock exception while reading your reply. 

Would you be okay with me opening a new issue to track adding back the execute_after_commit feature?

**Comment by magnusvk** [comment]
Yeah good call to move this to a new issue!
