### ISSUE TITLE
Counter Culture multiple column updating same counter

### ISSUE THREAD

**Issue by NoNonsenseSolutions** [magnusvk/counter_culture#121]
i have in my battle class

```
class Battle < ActiveRecord::Base
  belongs_to :challenger,       class_name: 'User'
  belongs_to :opponent,         class_name: 'User'
  counter_culture :opponent,      column_name: "battles_count"
  counter_culture :challenger,      column_name: "battles_count"
end
```

which works fine.

However when i run
```
Battle.counter_culture_fix_counts
```
The tally no longer matches, i assume because one of the counter culture is overriding the other.

How do i go about doing this

**Comment by magnusvk** [comment]
`counter_culture_fix_counts` is not designed to handle this scenario. It assumes that each counter column corresponds to one counter_culture declaration. I would advise just writing up your own methods that resets the counts according to this logic. Otherwise, I'd be happy to look at a PR. :smile:
