### ISSUE TITLE
Remove unnecessary COALESCE statement

### ISSUE THREAD

**Issue by key88sf** [magnusvk/counter_culture#122]
The gem requirements (and the migration generator) specify that the counter column is `integer` and `NOT NULL`, however the generated counter update SQL uses `COALESCE` which seems unnecessary.

example generated SQL:
```
SQL (0.5ms)  UPDATE "products" SET "quantity_in_stock" = COALESCE("quantity_in_stock", 0) - 1 WHERE "products"."id" = $1  [["id", 11954]]

```

**Comment by magnusvk** [comment]
What's the downside of leaving the COALESCE there? What if someone does the migration manually and forgets to put the not null there?

**Comment by key88sf** [comment]
One reason is that it enforces data integrity if the non-null is actually respected by the code (and raising an error if it's null). If the COALESCE is left there, you might not even realize you have a potential data problem (or bugs in your code) where something should never be null but actually is.

Another reason is just to use the minimal amount of sql necessary to get the job done. We could add COALESCE and similar functions to lots of statements to guard against the "just in case it's null or messed up" situation, but that's generally bad practice, especially with databases. If somethign is supposed to be non-null, then typically it's a good idea to enforce that at the database level, and write SQL accordingly.

**Comment by magnusvk** [comment]
Hm; I just think that enforcing `NOT NULL` here isn't actually important and it's not something that this gem does. If you left the column to be nullable, it will just treat `NULL` as 0. And that seems entirely reasonable given that `nil.to_i == 0`. Plus, this is consistent with the way Rails' default counter caches work.

Thanks for following up here, but I'm still leaning towards leaving this as is.
