### ISSUE TITLE
counter_culture_fix_counts does not set count to zero

### ISSUE THREAD

**Issue by dimitrid** [magnusvk/counter_culture#124]
When running counter_culture_fix_counts, counters with zero counts do not get updated.
For example, if a counter is incorrectly showing 1 but the correct count is 0, counter_culture_fix_counts will not change it to zero.

**Comment by magnusvk** [comment]
This stuff is pretty thoroughly tested, so I'd be surprised if this was the case. But I might be wrong... If so, please fork the repo and open a pull request with a failing test I can use to reproduce this. Then I'll be happy to work on a fix. Thanks.
