### ISSUE TITLE
Touching with lock_version

### ISSUE THREAD

**Issue by holden** [magnusvk/counter_culture#136]
Hi, 

Using the `counter_culture :category, :touch => true` works fine for updating datetime stamps but it doesn't work with optimistic `lock_version` columns (it doesn't bump the version number on recalculation).  Is there a reason for this?  And/or some way around this. I'm using it for a shopping cart type solution with quantity updates.  I would like these to bump the `lock_version` somehow when quantities change.

Thanks,

**Comment by magnusvk** [comment]
counter_culture doesn't call `touch` on the model, it updates the timestamp directly. [See here](https://github.com/magnusvk/counter_culture/blob/28f938477250ad6001cf0d70dfe0b4d908130c7b/lib/counter_culture/counter.rb#L53). I'd be open to adding support for bumping the `lock_version` there if you wanted to open a PR.
