### ISSUE TITLE
Conditional counter caches breaks when setting 1 of the dynamic column names to nil

### ISSUE THREAD

**Issue by trostli** [magnusvk/counter_culture#144]
On my Download model I have the following counter_culture set:

```
counter_culture :sample,
                  :column_name => proc { |download| download.downloaded_at >= 1.day.ago ? 'recent_downloads_count' : nil },
                  :column_names => {
                    ["downloaded_at >= ?", 1.day.ago] => 'recent_downloads_count',
                    ["downloaded_at < ?", 1.day.ago] => nil
                  }
```

However when I run `Download.counter_culture_fix_counts` I eventually will get the error:

```
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "LEFT"
LINE 1: ...downloads.id)*1 AS count, samples. FROM "samples" LEFT JOIN ...
                                                             ^
: SELECT  samples.id, samples.id, COUNT(downloads.id)*1 AS count, samples. FROM "samples" LEFT JOIN downloads AS downloads ON samples.id = downloads.sample_id AND (downloaded_at < '2016-10-19 15:04:25.570433') GROUP BY "samples"."id"  ORDER BY "samples"."id" ASC LIMIT 1000
```

If I change the dynamic columns names to:

```
                  :column_names => {
                    ["downloaded_at >= ?", 1.day.ago] => 'recent_downloads_count',
                    ["downloaded_at < ?", 1.day.ago] => 'recent_downloads_count'
                  }
```

The counter_culture_fix_counts command runs smoothly but gives me the wrong count. Am I missing something? Are you not allowed to set a column name to nil?

Thanks in advance

**Comment by magnusvk** [comment]
Hm; this looks like it should work. Seems that you hit on a real bug...

**Comment by trostli** [comment]
Hi @magnusvk ,

Just wanted to let you know I've been able to resolve the issue and get the correct count by simply removing the condition that set the column name to nil. The working method looks like this now:
```
counter_culture :sample,
                  :column_name => proc { |download| download.downloaded_at >= 1.day.ago ? 'recent_downloads_count' : nil },
                  :column_names => {
                    ["downloaded_at >= ?", 1.day.ago] => 'recent_downloads_count'
                  }
```

**Comment by magnusvk** [comment]
👍 thanks for the update.

**Comment by magnusvk** [comment]
I "fixed" this by just making `fix_counts` do nothing when the column name is nil. Thanks for reporting this, and good you figured out the solution. 😄

**Comment by trostli** [comment]
Glad I could help 👍

**Comment by avinoth** [comment]
@magnusvk So, when would this be published to Rubygems? done for now using github, just for confirmation
