### ISSUE TITLE
Pessimistic locking

### ISSUE THREAD

**Issue by key88sf** [magnusvk/counter_culture#146]
WDYT about adding an option to do pessimistic locking on the model that needs the counter updated? Right now there is just a normal `SELECT * from model_name...` followed by an `UPDATE model_name SET counter_col = COALESCE(...) ...`.

Would like this to be:
```
SELECT * from model_name...  FOR UPDATE
UPDATE model_name SET counter_col = COALESCE(...) ...
```

**Comment by magnusvk** [comment]
Are you talking about the `fix_counts` case, or the normal update? In the normal update [it doesn't include the original value in the UPDATE statement it issues](https://github.com/magnusvk/counter_culture/blob/master/lib/counter_culture/counter.rb#L55), thus making it atomic and not needing any locking.

So, for example, `UPDATE models SET counter_col = COALESCE(counter_col, 0) + 1` is an atomic SQL statement that needs no locking.

Am I missing something?
