### ISSUE TITLE
Conditional counter caches ignore updates

### ISSUE THREAD

**Issue by pawel1892** [magnusvk/counter_culture#147]
counter_culture :product,
                  column_name: proc {|model| model.visible? ? 'visible_count' : nil },
                  :column_names => {
                      ["products.state = ?", 'visible'] => 'visible_count',
                  }

I have a counter_cache that looks like this. If I update the state of a product the visible_count does not change. Am I missing something or is there a bug?

**Comment by magnusvk** [comment]
There's a test in the suite [that checks for exactly this case](https://github.com/magnusvk/counter_culture/blob/master/spec/counter_culture_spec.rb#L439). My guess would be that the bug is somewhere else. But if you can come up with a failing test for this, I'd be happy to take another look.
