### ISSUE TITLE
Dynamic Column Names with Totalling isn't showing correct changes in wrong key

### ISSUE THREAD

**Issue by kmcgaire** [magnusvk/counter_culture#148]
Combining these two features 
https://github.com/magnusvk/counter_culture#handling-dynamic-column-names
https://github.com/magnusvk/counter_culture#totaling-instead-of-counting

into something that looks like
```ruby
  counter_culture [:person],
    :column_name => proc {|model| model.earns_money? ? 'total_money_earned' : 'total_money_spent' },
    :column_names => {
          ["transaction.monetary_value > 0"] => 'total_money_earned',
          ["transaction.monetary_value <= 0"] => 'total_money_spent'
      },
    :delta_column => 'monetary_value'
```

Lets say we have an incorrect value for `total_money_earned` of 100 when it should be 200. Running
```ruby
Transaction.culture_counter_fix_counts
```
I would expect to return
```ruy
=> [{:entity=>"Person",
  :id=>1,
  :what=>"total_money_earned",
  :wrong=>100,
  :right=>200}]
```
However we actually get
```ruby
=> [{:entity=>"Person",
  :id=>1,
  :what=>"total_money_earned",
  :wrong=>nil,
  :right=><BigDecimal:7fa5802ce7f0,'0.0',9(18)>}]
```

I believe the :wrong key here should be 100.

Also if the previous value was 0 and the correct value should be 0, and entry still exists with wrong=nil, and a BigDecimal of 0

**Comment by magnusvk** [comment]
It's quite possible this is broken. There isn't a specific test for this. It's kind of hard for me to reproduce this, though, without access to your data / codebase. Could you create a pull request with a failing test, though? That way I can reproduce or fix. (Or if you just want to pull-request the fix that'd be even better. ;) )
