### ISSUE TITLE
Support callback

### ISSUE THREAD

**Issue by mollerhoj** [magnusvk/counter_culture#155]
I need to save state transitions when the my counters change. That is, whenever `cities.people_count` is increased, I want to create a `CityStateChanged` record.

It seems there is no support for specifying a method to be called after counts are updated . If I create a PR, would you be willing to support this feature?

**Comment by magnusvk** [comment]
Wouldn't it be easier / more reliable to do this in an after_create / after_destroy hook on the model that causes the count to change? Just trying to save you some work here. :)

I'd be happy to consider a PR for this, though. Looks like [here](https://github.com/magnusvk/counter_culture/blob/master/lib/counter_culture/counter.rb#L57) would be the place the callback would get called.
