### ISSUE TITLE
Support Max Value

### ISSUE THREAD

**Issue by kidbombay** [magnusvk/counter_culture#158]
I'm trying to get the max value of an associated model
```
counter_culture :user, column_name: :years_experience, delta_column: :years, touch: true
```
But this adds up the total years. What I want is the max(years) value.

**Comment by magnusvk** [comment]
Getting the `MAX()` value is not currently supported but I'd be happy to look at a pull request if you added support. :)

**Comment by kidbombay** [comment]
Ok I will start on this, any hints on where to start in the code base?

**Comment by magnusvk** [comment]
You may want to look at how the `delta_column` stuff works; though the `MAX()` support would be slightly different in that it has to keep in mind the rest of the table. Still. :)

**Comment by doutatsu** [comment]
Was there ever an update on this? Looking for the something like this myself

**Comment by magnusvk** [comment]
Unfortunately not, no. Still would be happy to look at a PR though. 😉

**Comment by MyklClason** [comment]
Here is a straightforward approach for getting the max and min of the "years" column. We create columns to store how the max/min should be adjusted, then use the "sum" columns approach to total up the adjustments. If there is no change to the min/max, the adjustment should be zero. The only issue is that these columns may need to allow for a "nil" to handle the "unset" state. However, a different flag could theoretically be used. IE: -1 if you expect only positive values to be valid. 0 can also be a valid flag too (viable for max, but not really min) but that may introduce invalid data, so care must be used.

(the touch is probably optional)

```
counter_culture :user, column_name: :max_years, delta_column: :max_years_adjustment, touch: true
counter_culture :user, column_name: :min_years, delta_column: :min_years_adjustment, touch: true

before_save :standardize

def standardize
  self.min_years_adjustment = user.years_experience.nil? ? years : [years, user.years_experience].min - user.years_experience
  self.max_years_adjustment = user.years_experience.nil? ? years : [years, user.years_experience].max - user.years_experience
end
```

(I haven't tested the above code but should be close)
