### ISSUE TITLE
Undefined method has_one? for ActiveRecord::Reflection::AssociationReflection

### ISSUE THREAD

**Issue by rvracaric** [magnusvk/counter_culture#160]
When running `counter_culture_fix_counts` on Rails 3.2.22.5, getting:

```
NoMethodError: undefined method `has_one?' for #<ActiveRecord::Reflection::AssociationReflection:0x007f9685835d10>
```

from:
```
counter_culture-1.1.1/lib/counter_culture/reconciler.rb:133:in `block in join_clauses'
```

If I'm not mistaken `ActiveRecord::Reflection::AssociationReflection#has_one?` is only available from Rails 4.2.1 onward?

http://apidock.com/rails/v4.2.1/ActiveRecord/Reflection/AssociationReflection/has_one%3F

Downgrading to `counter_culture 1.0.0` got rid of the crash and `counter_culture_fix_counts` was able to complete successfully.

**Comment by magnusvk** [comment]
@rvracaric yup good point. It turns out that feature wasn't working anyhow. 😄 So I've removed it.

I've added automated testing for older Rails versions so I can catch this more easily in the future. 

Version 1.3.0 should work for you again.
