### ISSUE TITLE
Polymorphic Relation with nil parent faults attempting to update counter cache

### ISSUE THREAD

**Issue by Tongboy** [magnusvk/counter_culture#167]
I have a model with a relation to polymorphic parents that can also not belong to any of those parents.

something like:
Person belongs_to: :employer, polymorphic: true

Company has_many :persons, as: :employer
NonProfit has_many :persons, as: :employer

When the Person doesn't have an employer (employer_type column is nil) counter_culture raises an exception when the model is saved or counter_culture_fix_counts is run - it looks like the employer_type of nil tries to get constantized and fails (because there isn't an employer association for that instance)

full stack:
```
NoMethodError: undefined method `constantize' for nil:NilClass
	from /home/jchurch/.rvm/gems/ruby-2.3.2/gems/counter_culture-1.5.0/lib/counter_culture/counter.rb:176:in `relation_klass'
	from /home/jchurch/.rvm/gems/ruby-2.3.2/gems/counter_culture-1.5.0/lib/counter_culture/counter.rb:230:in `relation_primary_key'
	from /home/jchurch/.rvm/gems/ruby-2.3.2/gems/counter_culture-1.5.0/lib/counter_culture/counter.rb:128:in `foreign_key_value'
	from /home/jchurch/.rvm/gems/ruby-2.3.2/gems/counter_culture-1.5.0/lib/counter_culture/counter.rb:35:in `change_counter_cache'
	from /home/jchurch/.rvm/gems/ruby-2.3.2/gems/counter_culture-1.5.0/lib/counter_culture/extensions.rb:119:in `block (2 levels) in _update_counts_after_update'
	from /home/jchurch/.rvm/gems/ruby-2.3.2/gems/counter_culture-1.5.0/lib/counter_culture/extensions.rb:108:in `each'
	from /home/jchurch/.rvm/gems/ruby-2.3.2/gems/counter_culture-1.5.0/lib/counter_culture/extensions.rb:108:in `block in _update_counts_after_update'
	from /home/jchurch/.rvm/gems/ruby-2.3.2/gems/counter_culture-1.5.0/lib/counter_culture/extensions.rb:80:in `_wrap_in_counter_culture_active'
	from /home/jchurch/.rvm/gems/ruby-2.3.2/gems/counter_culture-1.5.0/lib/counter_culture/extensions.rb:107:in `_update_counts_after_update'

```

a potential workaround I've found if I set the association_type column (in my above example employer_type) default to one of the valid associations (ie 'Company') then counter_culture runs correctly. 

However setting that column to a 'wrong' string when there isn't a relation is something I'd like to not do.

any help/thoughts/options would be greatly appreciated, thank you!

**Comment by magnusvk** [comment]
Thanks for reporting this, @Tongboy. This should be fixed in version 1.5.1, released just now.
