### ISSUE TITLE
counter_culture_fix_counts doesn't work well if counter model has after_find callback

### ISSUE THREAD

**Issue by Looooong** [magnusvk/counter_culture#168]
```rails
class Test
  has_many :answers

  after_find :evaluate, if: :expired?

  def expired?
    # Throws ActiveModel::MissingAttributeError
    self.expired_at < Time.now
  end

  def evaluate
  end
end

class Answer
  belongs_to :test

  counter_culture :test, column_name: lambda { |record| record.correct? ? :correct_answers_count : nil }

  def correct?
    true
  end
end
```

If I run `Answer.counter_culture_fix_counts`, `Test#expired?` will throw `ActiveModel::MissingAttributeError`. This happens because `counter_culture` only `select` few columns related to count (`id` and `correct_answers_count` in this case).

A workaround by rescuing exception would be very ugly (`Test#expired?` is not the only one to throw error).

Can you add an option to `counter_culture` or `counter_culture_fix_counts` to select all the fields of the parent when finding? Thanks a lot.

**Comment by magnusvk** [comment]
This isn't supposed to work without you specifying the extra column_names argument, as documented here: https://github.com/magnusvk/counter_culture/blob/master/README.md#handling-dynamic-column-names

Arguably this could show a more informative error message, but this should fix it for you.

**Comment by Looooong** [comment]
@magnusvk I forgot to include `column_names` here, but I did have `column_names` when fixing the count. The problem is just like I said before, `counter_culture` would `find` model by `select` some if its columns, preventing callback like `after_find` accessing other attributes that's not `selected`.

**Comment by magnusvk** [comment]
@Looooong ahh, I see now. Your best bet would probably be to disable the `after_find` when you're using `counter_culture_fix_counts`. It wouldn't be used anyhow, counter_culture will only do an `update_all` regardless that skips all other callbacks. I'd consider a PR that adds this functionality, but this hasn't come up before so I'd consider this to be a pretty rare use case and not something that I'd work on myself.
