### ISSUE TITLE
Problem when using callbacks on counter-cache model (e.g. Papertrail)

### ISSUE THREAD

**Issue by key88sf** [magnusvk/counter_culture#171]
Hi - wondering about the best way to handle this situation:
* We have a parent model that has the count column.
* Also on this parent model we are using the Papertrail gem, and we want to record changes to the count column.

Problem --> when the count column is updated from counter_culture, the update is happening via 
an `update_all` statement:
counter.rb#67:
`klass.where(relation_primary_key(relation) => id_to_change).update_all updates.join(', ')`

which doesn't fire callbacks on the parent model and thus doesn't trigger Papertrail (or anything that relies on callbacks).

Is the reason the `update_all` is used instead of `update` purely for performance (i.e. no need to instantiate an actual object), or something else (perhaps circular callbacks, etc)? Any ideas on the best way to support things which rely on callbacks being fired on the parent?

Thanks!

**Comment by magnusvk** [comment]
Performance is definitely a concern here; so is potential circular callbacks. I see what you're trying to do, and that makes sense to me, but it's not something that's currently supported. I'd be open to a PR that adds an option for this, but I'd want to keep the current default behavior. I don't have a need for this, so won't work on it myself. But again, very open to a PR. 😄 

The only other idea I'd have here is to add Papertrail to the counted model instead; then you could reconstruct the count. But that's pretty involved and not really what you're looking for.

Sorry I can't be more helpful here!
