### ISSUE TITLE
Conditional counts not updating as expected

### ISSUE THREAD

**Issue by CodingAnarchy** [magnusvk/counter_culture#177]
I am working with a `Child` class with an `active` boolean field, and this conditional count to reference another model:

```Ruby
column_name: proc { |model| model.active? ? 'children_count' : nil }
```

When adding one of these child classes to another model with the counter, the `active` flag is not being appropriately handled.

The `<<` methodology will always add to the counter in memory, but will be rejected upon reloading the instance, regardless of whether `child.active?` is `true` or `false`.  Additionally, `children.delete(child)` on the association will always reduce the count, regardless of the `active?` check, while `child.delete` has not adjusted the count at all.

I would expect that only the `active` child instance would produce an increase or decrease in the counts as expected.  If needed, I can reproduce my specs that demonstrate this odd behavior.

**Comment by magnusvk** [comment]
You don't have enough information here to figure out what's going on, unfortunately. I don't even know what kind of ActiveRecord relationship you're using between these two classes.

Could you open a pull-request with a failing test for me?

**Comment by CodingAnarchy** [comment]
I've opened #178 as a pull request with some failing tests.

The ActiveRecord relationship is a basic `has_many`, and I was looking to cache just the `active` count of the subordinate class.

**Comment by CodingAnarchy** [comment]
I've got it working as expected now.  Thanks for the help.  I'll close this issue.
