### ISSUE TITLE
Carrierwave with amazon s3 not work with counter_culture gem

### ISSUE THREAD

**Issue by shir** [magnusvk/counter_culture#18]
If you create model like this

``` ruby
class UploadTest < ActiveRecord::Base

  belongs_to :category

  attr_accessible :category_id, :something

  mount_uploader :something, PhotoUploader

  counter_culture :category
end
```

with uploader connected to s3 (fog and carrierwave-aws backends have same behavior) after updating file only file name in database is updated, but new file on s3 is not uploaded (old file stays on s3). This issue only on updating file, creating new object works ok.

I've created [same issue](https://github.com/carrierwaveuploader/carrierwave/issues/1127) in carrierwave project.

**Comment by danielevans** [comment]
@magnusvk I have. I have uploads which fail to save the file (both s3 and file stores) and commenting out the model's `counter_culture` line fixes it. Also overriding `_update_counts_after_update` to a no-op eliminates the error but overriding `after_commit_action`'s `_after_commit_hook` does *not* eliminate the problem. I'm still investigating and hope to find problem.

**Comment by danielevans** [comment]
I've found the problem, and it is not a bug in `counter_culture`. The problem is that carrierwave is not properly handling the `dup` and there is already a PR to fix it: https://github.com/carrierwaveuploader/carrierwave/pull/1544
