### ISSUE TITLE
Decrement counter on object creation

### ISSUE THREAD

**Issue by SergejOvsiannikov** [magnusvk/counter_culture#183]
I have a strange question.

Is there a way to decrement counter on object creation, reverse logic.

I have two models addition and subtraction. When an object was created in addition I want to increment counter like in normal flow, but if an object was created in subtraction I want to decrement the counter.   

This is not typical flow for a counter, but I believe that this has the right to exist.

Maybe there is a better way to do this, I need a history of transactions but I don't want to calculate result dynamically every time.ou

If this not an issue for this gem, feel free to close this ticket.

Thank you for your time.

**Comment by magnusvk** [comment]
It sounds like you are looking for the [delta_magnitude](https://github.com/magnusvk/counter_culture#delta-magnitude) option here.
