### ISSUE TITLE
Does `batch_size` config fix my problem?

### ISSUE THREAD

**Issue by jamesfzhang** [magnusvk/counter_culture#185]
Hi, I'm currently running into issues with Rail's default `counter_cache: true`, where there are too many `UPDATE "polls" SET "votes_count" = COALESCE("votes_count", 0) + 1 WHERE "polls"."id" = 1` statements and it's backing up my database. Does the `batch_size` configuration fix this problem? Thanks.

**Comment by magnusvk** [comment]
No, `batch_size` is only an option for `counter_culture_fix_counts`. The queries you are seeing would be triggered by object creations that increase the count. counter_culture will always trigger a query like the above for every `INSERT`, but that's of course intended behavior. That should be a quick, atomic query though, and I haven't heard about it causing issues before.

**Comment by jamesfzhang** [comment]
Thanks for the response. There usually isn't a problem with this specific query. However, the product I'm working on experiences a burst of traffic on certain occasions where there would be 50k inserts for one association (in this case, 50k votes on 1 poll in a minute), and you see the same `UPDATE "polls" SET "votes_count" = COALESCE("votes_count", 0) + 1 WHERE "polls"."id" = 1` repeated 50k times, causing performance issues. Will explore other options. Thank you!
