### ISSUE TITLE
Conditional counter fails update on multi-level cache

### ISSUE THREAD

**Issue by CodingAnarchy** [magnusvk/counter_culture#186]
I have an arrangement like this:

```ruby
class Child < ActiveRecord::Base
  has_many :parent_privileges, dependent: :destroy
  has_many :parents, through: :parent_privileges

  counter_culture [:parent_privileges, :parent], column_name: proc { |model| model.active? ? 'children_count' : nil }, column_names: {['children.active = ?', true] => 'children_count'}
end

class ParentPrivilege < ActiveRecord::Base
  belongs_to :child
  belongs_to :parent
end

class Parent < ActiveRecord::Base
  has_many :parent_privileges, dependent: destroy
  has_many :children, through: :parent_privileges
end
```

This `counter_culture` works fine with `Child.counter_culture_fix_counts`, but fails on an update to the `active` field of the Child instance (for instance, `Child.first.update(active: false)` with `NoMethodError: undefined method 'child_id_was' for #<Child:0x007fdd43b69478>`.  It appears to not be going off the hierarchy as I expect.

My question: is this a bug I stumbled across, or am I doing something invalid by having the `belongs_to` class in the middle of the hierarchy?

**Comment by magnusvk** [comment]
Yes, you want the `counter_culture` call on the model that has the `belongs_to` relationship. I should clarify this in the documentation. Also, this probably still doesn't do what you want here as the count then wouldn't be updated on changes to `active` in the child. My guess is that that wouldn't currently be possible with just counter_culture code.
