### ISSUE TITLE
Anyway to set rules for whether a record should be counted?

### ISSUE THREAD

**Issue by jisaacks** [magnusvk/counter_culture#193]
I have leads and listings, I am trying to keep track of how many listings a lead as viewed. I have an event record that gets created every time a lead views a listing.

This event is using counter culture like so:

```ruby
class Event::ViewedListing < Event
  counter_culture :lead, column_name: 'viewed_listing_count'
end
```

The problem is, if a lead views the same listing multiple times, it creates several events. This I want, but it also causes the "views" to go up. I only want to count the views for unique listings.

There are two fields on the event that identify the listing, `mls_id` and `mls_listing_id`. Is there a way to tell counter culture to only count a set of events with uniq `[:mls_id, :mls_listing_id]` fields?

Say for example I have 3 events belonging to a lead with the following mls_id and mls_listing_id values:

| mls_id | mls_listing_id |
|--------|----------------|
| foo    | 1              |
| foo    | 1              |
| foo    | 2              |
| bar    | 1              |

This should only count as 3 unique views because [foo, 1] was viewed twice.

Can this be achieved?

**Comment by magnusvk** [comment]
Not natively, no. And I can't think of a hack to accomplish this right now, either.

**Comment by jisaacks** [comment]
OK, thanks I assumed this wasn't supported based on what I read in the docs, just wanted to make sure I wasn't missing something.

Thanks.
