### ISSUE TITLE
Split counter_culture_fix_counts into several jobs

### ISSUE THREAD

**Issue by mojobiri** [magnusvk/counter_culture#194]
Hi.
Is there a way to split `counter_culture_fix_counts` execution into several jobs?
So i could do `Contact.where(id: [...]).counter_culture_fix_counts` or something similar.
I have a lot of records and want to run update in multiple sidekiq threads so it complete faster. But in order to do that I need a mechanism to pass in ids, start_from or something..
Thanks!

**Comment by magnusvk** [comment]
There is not. That's a great idea, though. I'd love to see a PR for that! :)
