### ISSUE TITLE
Unable to pass in #batch_size to counter_culture_fix_counts

### ISSUE THREAD

**Issue by mojobiri** [magnusvk/counter_culture#196]
Hi.
Looks like following line is making an issue [there](https://github.com/magnusvk/counter_culture/blob/be0625c05ec94da37e9bba3861be3750467ae36c/lib/counter_culture/extensions.rb#L66)
```ruby
reconciler = CounterCulture::Reconciler.new(counter, options.slice(:skip_unsupported))
```

**Comment by magnusvk** [comment]
@mojobiri fixed in 1.8.2.
