### ISSUE TITLE
Updating counters of a single record with dynamic column names

### ISSUE THREAD

**Issue by alagos** [magnusvk/counter_culture#206]
I have the following counters:

```ruby
  counter_culture :order
  counter_culture :order, column_name: proc { |m|
    'checked_messages_count' if m.checked_at.present?
  }, column_names: {
    'messages.checked_at IS NOT NULL' => 'checked_messages_count'
  }
```
and this method:
```ruby
  def self.check_by(user)
    update_all(checked_at: Time.zone.now, checked_by_id: user.id)
  end
```
So I was thinking that changing `checked_at` from `nil` to something would update the `checked_messages_count` counter, but it wasn't.
Calling `Message.counter_culture_fix_counts` fixed the counters, but I'm willing to update the counters only for the order associated to my message.  
Is there a way with c_c to update just this single order or I must to do it manually?

**Comment by magnusvk** [comment]
`update_all` doesn't run callbacks, so there's no way for counter_culture to know that you're checking values. You'd have to iterate over the records and `update_attributes` on them instead.
