### ISSUE TITLE
Accept Static Delta Magnitude when Delta Column present

### ISSUE THREAD

**Issue by PilotCurly99** [magnusvk/counter_culture#208]
I ran into an issue where I need to change the sign on a totaling function when using delta column.  When I dug in it appears that the delta_magnitude is ignored when a delta_column is present.  I think I follow the logic to do this when the delta magnitude is a Proc, but I think it would be a very small change to allow it to accept a static magnitude (in my case -1).  If the delta magnitude was a Proc it would just set it to a static value of 1 (essentially ignore it).

I can submit a PR to add this functionality, but just wanted to see if this made sense to anyone else or if I was missing something.  Thanks!

**Comment by magnusvk** [comment]
@PilotCurly99 I'm not 100% sure I understand what you're trying to do. Couldn't you just use `delta_magnitude: proc {|model| -1 * model.delta_column}`, without using the delta_column at all? That seems simpler and more straightforward to me.

**Comment by PilotCurly99** [comment]
Thank you, @magnusvk . Here's an example where delta_magnitude appears to be ignored. If there is a simpler way to achieve this, I am missing it.  I want it to subtract the value of amount_cents from the parent model column of repayment_cents.

`counter_culture :company_account, column_name: proc {|model| model.repayment? && model.reconciled? ? 'repayment_cents' : nil }, delta_column: "amount_cents", delta_magnitude: -1`

**Comment by PilotCurly99** [comment]
I see what you are saying now.  Disregard.  Closing issue.  Thanks for the help!
