### ISSUE TITLE
Issues in testing

### ISSUE THREAD

**Issue by victor-seo** [magnusvk/counter_culture#21]
The counters doesn't seem to update well in test environment.

Let's go with three models User, Product, and Purchase, where a user has_many products through purchases. User is counting purchases. 

When I run @user.products.push(@product), it seems to update the counter just fine.
However, @user.purchases.create(product: @product) does not update the counter. I have to run Purchase.counter_culture_fix_counts in order to get the test passing.

I have to use 'create' instead of 'push' for various reasons. Using create works fine in real use cases, but it doesn't work in test environment. 

Running counter_culture_fix_counts in test is not a big deal, but it would be good to get it working without running the fix method.

**Comment by bluej100** [comment]
I found this page because I was using `DatabaseCleaner.strategy = :transaction` and counter_culture delays its writes until after the commit. I just needed to switch to truncation for the test.
