### ISSUE TITLE
Documentation request - when does the update run?

### ISSUE THREAD

**Issue by ConfusedVorlon** [magnusvk/counter_culture#213]
assuming I'm not using execute_after_commit - can you specify in the docs where in the callback chain the updates happen?

I currently have a case where the counter update seems to have happened by the time an after_save callback runs on my model.

I'm not sure whether this is luck (just happened to be be earlier in the list of after_save callbacks), or design (counter_culture runs in an earlier callback altogether)

would be great if you could cover this in the docs.

thank you.

**Comment by magnusvk** [comment]
@ConfusedVorlon it registers callbacks when you call `counter_culture` in your model, so this will depend on whether you call `counter_culture` first or register your own callbacks first.
