### ISSUE TITLE
rollback migartion  FOREIGN KEY issue!

### ISSUE THREAD

**Issue by dcalixto** [magnusvk/counter_culture#215]
after setup the gem i tried to rollback the migration and BANG!  a migration issue!

```
SQLite3::ConstraintException: FOREIGN KEY constraint failed: DROP TABLE "tags"
/home/daniel/bompot/db/migrate/20180404165923_add_tags_count_to_tags.rb:7:in `down'
```
someone with the same issue with rails 5

**Comment by magnusvk** [comment]
If you look at the database migration template, it doesn't include a drop table so this is unrelated to counter_culture:
https://github.com/magnusvk/counter_culture/blob/master/lib/generators/templates/counter_culture_migration.rb.erb

**Comment by Genkilabs** [comment]
FYI this is a core Rails break and was fixed here: https://github.com/rails/rails/pull/32865/commits/45881b0a64b4039e3b0d27e2c4d959dc2d744b9d
Currently on master but unreleased on 5.2.0
