### ISSUE TITLE
Update columns_count from Multi-level counter with condition

### ISSUE THREAD

**Issue by mrjusepelo** [magnusvk/counter_culture#223]
Hello,
My structure is this:

ModelProduct
counter_culture [:subcategory, :category]

Thank you!

**Comment by magnusvk** [comment]
I don't understand why you opened this issue; is there a question or a problem here that I don't understand?

**Comment by mrjusepelo** [comment]
I'm sorry,
How to do a counter cache to products with status active  ?
Is posible have two counter cache (actives and inactives) from model Product?

Thank you!

**Comment by magnusvk** [comment]
This looks like the documentation you're looking for: https://github.com/magnusvk/counter_culture#dynamic-column-name

Also, issues are not a support hotline. Please try to read the documentation before you open an issue.
