### ISSUE TITLE
Timestamps not set when creating papertrail version row from counter update

### ISSUE THREAD

**Issue by key88sf** [magnusvk/counter_culture#224]
@magnusvk Another bug from using the new `save_with_version` function from Papertrail. The instance's `updated_at` is not being updated now with this new method. 

Papertrail uses the `updated_at` value of the instance to set the `created_at` timestamp on their new version row (presumably so it exactly matches the time the model itself was updated).

So now what we have happening is that version rows are created for the counter updates, but their `created_at` timestamps are not indicative of when the row was actually created. They are just set to whatever value happened to be in the `updated_at` column for the model itself.

I believe the fix for this is to simply set the `updated_at` of the instance inside of the `if instance.paper_trail.respond_to?(:save_with_version)` block, similar to what you do for "touch":

```
            if instance.paper_trail.respond_to?(:save_with_version)
              # touch_with_version is deprecated starting in PaperTrail 9.0.0
              current_time = instance.send(:current_time_from_proper_timezone)
              instance.send(:timestamp_attributes_for_update_in_model).each do |column|
                instance.send("#{column}=", current_time)
              end

              instance.paper_trail.save_with_version(validate: false)
            else
              instance.paper_trail.touch_with_version
            end
```

**Comment by magnusvk** [comment]
Fix released as 2.0.1. Thanks for contributing!
