### ISSUE TITLE
Counter should decrement on `really_destroy!` if not preceded by `destroy`

### ISSUE THREAD

**Issue by sarah-mostafa-m** [magnusvk/counter_culture#228]
the counter works successfully on create but not on delete, it does this when using really_destroy! from act_as_paranoid gem

**Comment by sarah-mostafa-m** [comment]
Yeah it decrements only on destroy, but doesnt it make sense that it should decrement on both destroy and really_destroy!?

**Comment by magnusvk** [comment]
It doesn't: If you started with an empty table, then created, then destroyed, then really destroyed a model, you'd end up with a count of -1 even though the table is now empty again. That doesn't make sense to me.

**Comment by sarah-mostafa-m** [comment]
Then in case of really_destroy! it should decrement only if not destroyed already

**Comment by magnusvk** [comment]
@sarah-mostafa-m ok, that's a good point. I don't have time to work on this given that I don't use these features. Do you have time to put together a pull request with a test?
