### ISSUE TITLE
change timestamp conditionally with counter_culture

### ISSUE THREAD

**Issue by kashifnaseer** [magnusvk/counter_culture#229]
counter_culture :project, touch: true,

This command changes updated_at of Project Model. I want to change this behavior and want to update timestamp conditionally, something like  

    counter_culture :project, touch: Proc.new {|participant| participant.project.created_by_data_entry_team?  },
How i can do it ?

**Comment by magnusvk** [comment]
This isn't possible, and I'd say this kind of thing falls outside of the scope of this project, so I'd even be hesitant to accept a PR for this.

**Comment by rmm5t** [comment]
🤔Hmm. I just came here looking for a similar feature. Here's my use-case, FWIW:

```ruby
class Project < ApplicationRecord
  belongs_to :thing

  counter_culture :thing, touch: :used_at
end
```

When a project is created or updated to point at thing1, I'd like `thing1.used_at` to be touched, but when the project is changed from `thing1` to `thing2`, I'd only like `thing2.used_at` to be touched.

Similarly, if a project is destroyed, I don't want `used_at` to be touched.

I think I could at least get my deletion and likely both behaviors accomplished  if `:touch` accepted a `proc` for a dynamic timestamp column, just like `:column_name`, etc does.

Might you reconsider this feature request?

**Comment by magnusvk** [comment]
Let me expand a bit on my reasoning for my earlier comment: This gem does counter caching. The touch logic was added only to allow changing the updated timestamp when the counter cache changes.

The change you're outlining seems unrelated the the purpose of counter caching. There's nothing wrong with what you're trying to do, I just don't think it belongs in this gem. I don't even clearly see how your work is made easier by doing it in the context of counter_culture.

Am I missing something here?

**Comment by magnusvk** [comment]
So... I'm always willing to look at a PR. If this ends up being an easy change with a couple of lines of code and good test coverage, I don't want to rule out pulling that in and maintaining it. But this seems ancillary enough to the primary use case here that I am really hesitant, particularly if it appears like a big change and thus maintenance burden on my part.

If you want to go ahead and try and make this work, do feel free to open a PR, just don't be surprised if I look at it and still say "nope, doesn't belong in this gem." I'm trying to be upfront here to make sure you don't end up doing a lot of work for naught if that's the case.

**Comment by rmm5t** [comment]
All fair. I get it.  I’ll try to find time for a PR later this week. Your call after that.
