### ISSUE TITLE
Fixing counter caches not supported when :delta_magnitude is a Proc

### ISSUE THREAD

**Issue by archonic** [magnusvk/counter_culture#230]
I've hit this when trying to fix counter_culture counts:
```
Fixing counter caches is not supported when :delta_magnitude is a Proc; you may skip this relation with :skip_unsupported => true
```

Is there no way to tell it to just do it anyway? Do I have iterate over every record and manually set the cache column myself?

**Comment by magnusvk** [comment]
Yes. That's what this message says, right?

Or feel free to open a pull request that adds support for this to counter_culture.

**Comment by archonic** [comment]
Perhaps you could help me with some syntax. I'm not sure how to provide `:column_names` to the `counter_culture_fix_counts` method. Looking at the code hasn't helped so far and it's not in the examples in the readme.

In my app, a Section has many Comments. I have this on my Comment model:
```
counter_culture :section, column_name: proc { |comment| comment.open_status? ? :open_count : :closed_count }
```

How can I fix the count for both `open_count` and `closed_count`? The method looks to accept a hash but I'm not sure what the key and value are meant to be. All my experimentation keeps getting `Must provide :column_names option for relation [:section] when :column_name is a Proc; you may skip this relation with :skip_unsupported => true)`.
