### ISSUE TITLE
Scoping polymorphic counters to specific related entity

### ISSUE THREAD

**Issue by etcook** [magnusvk/counter_culture#233]
I noticed that at one point, there was a :polymorphic_associated_models param, but it was removed in favor of inferring them.  I'm only interested in countering one of the polymorphic relationships. Is the accepted pattern to proc these conditionally or is there a way to define the specific polymorphic entities that you're interested in counting?

**Comment by magnusvk** [comment]
This isn't something that has come up before; there is no way to define the specific polymorphic entities you would like to count. If using a proc to do this conditionally works for you, that sounds like a good way to approach this. I don't think we specifically test for this, though, so I'm not 100% sure it will work.

**Comment by etcook** [comment]
@magnusvk I don't understand why you say it hasn't come up before, when there was code to do just this in a PR that was removed. The issue with procs, in general, is that CC refuses to update the counters and you have to write manual routines. If you're going to have to write manual routines anyways, there's not much point in using CC.

Thoughts?
