### ISSUE TITLE
Issues with asynchronous simultaneous updates

### ISSUE THREAD

**Issue by timdiggins** [magnusvk/counter_culture#238]
I think that i'm having relatively frequent issues where two near-simultaneous updates are causing incorrect resultant counts (they are getting fixed by periodic counter_culture_fix_counts). 

My question is  whether my analysis is correct, and also checking if there is a mechanism in counter_culture to change the strategy from a increment/decrement basis to a count basis (slightly slower, but more resilient to this kind of issue)

Background (simplified):

I've got a counter for pupils that is dynamic based on a field in tests (FYI there are other counter_cultures defined on this model)

```
counter_culture :pupil, {
      column_name: proc { |model|
        (model.completed? && nil || "uncompleted_tests_count"
      },
      column_names: snipped
}
```

Two processes can update this -- a server-to-server callback action's sidekiq job and a redirect action. Mostly the redirect action happens first, and the redirect is responsible for marking the test as completed. However occasionally the callback's job happens first. The callback's job adds data to the test and also sets it as completed if it isn't already completed (just in case).

Occasionally they happen at roughly the same time. I've seen this happen (in logs) when trying to trace a "uncompleted_tests_count" that was set to -1.  (I see three  counter-culture decrements in the logs, while having only 2 total test models. Of the three counter culture decrements two come almost simultaneously (milliseconds apart) and from different sources (one web, one from a sidekiq job). 

However I notice that I also have other counter culture changes (increments in sidekiq jobs) that are also almost simultaneous which are both (I believe) duplicate sidekiq jobs. This is a known thing for  sidekiq  (and more generally for any at-least-once distribution  ). But in this case they don't seem to have doubly incremented the db.  

So I'm wondering why the difference in behaviour -- why does the increment/decrement mechanism within counter-culture (seem to) be idempotent with Sidekiq & similar near-but-not-totally simultaneous duplicate jobs, but not with two processes.

Is there something specific that does the deduplication of identical updates?  Or was it just luck in my case (where the specific timing of the two different cases were different ).

Is there any way of ameliorating this  in my configuration / use of counter culture?

**Comment by magnusvk** [comment]
@timdiggins counter_culture runs a thread-safe update in the database along the lines of `counter_column = COALESCE(counter_column, 0) + 1` so in the simple case concurrent updates shouldn't cause any issues. However, I could see how the use of a dynamic counter cache could be causing issues—if two threads simultaneously see this switch from uncompleted to completed, they might trigger two updates. I don't think there should be a difference from Sidekiq thread concurrency vs multiple process concurrency, though, so I'm guessing that's just a coincidence.

I can't think of anything off the top of my head that counter_culture could do to handle this automatically. Perhaps you could pessimistically lock the row before you start your changes in all the different spots, that should prevent this?
