### ISSUE TITLE
Rails 5.2.2, Polymorphic associations do not support computing the class.

### ISSUE THREAD

**Issue by jshow** [magnusvk/counter_culture#243]
When using counter_culture in a polymorphic chain, rails barfs when counter_culture tries to determine the klass of a relation

```
class Comment <  ApplicationRecord
  counter_culture [:medium, :page, :story], column_name: :comment_count
  belongs_to :medium
end
```
the :page relation in :medium is polymorphic

the flavour of the barf is
```
Polymorphic associations do not support computing the class.
```

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/reflection.rb#L421

**Comment by magnusvk** [comment]
counter_culture only supports polymorphic associations of one level: https://github.com/magnusvk/counter_culture#polymorphic-associations

You're trying to do this with a multi-level counter cache which is not supported.

Admittedly, the error message here isn't great, sorry about the confusion.
