### ISSUE TITLE
counter_culture_fix_counts does not work properly with dynamic columns

### ISSUE THREAD

**Issue by MobileD2** [magnusvk/counter_culture#245]
Hi,

I have dynamic column set for counter_culture but when I tried to run `Order.counter_culture_fix_counts` in rails console to update counters, it raises me an error:

`RuntimeError (Must provide :column_names option for relation [:order_group] when :column_name is a Proc; you may skip this relation with :skip_unsupported => true)
`

My setup: Rails 5.2, counter_culture 2.1.2
Order and OrderGroup have `close_base_amount` field

Order.rb

```
class Order < ApplicationRecord

  belongs_to :order_group, touch: true

  counter_culture :order_group, column_name: proc{ |model| model.opened? ? :open_orders_count : nil }

  scope :opened, ->{ where(arel_table[:close_base_amount].eq(0)) }

  def opened?
    close_base_amount.zero?
  end
}
end
```

OrderGroup.rb

```
class OrderGroup < ApplicationRecord

  has_many :orders

  scope :opened, ->{ where(arel_table[:close_base_amount].eq(0)) }

end
```

also I added a column to OrderGroup model by migration

```
class AddCountersToOrderGroups < ActiveRecord::Migration[5.2]
  def change
    add_column :order_groups, :open_orders_count, :integer, null: false, default: 0
  end
end
```

When I tried to add `column_names` to Order counter_culture configuration like this:

```
  counter_culture :order_group,
                  column_name: proc{ |model| model.opened? ? :open_orders_count : nil },
                  column_names: {
                      ["order_groups.close_base_amount = ?", 0] => :open_orders_count
                  }
```

it helps, but I think it does not make sense - I have to repeat all my conditions in `column_names` in SQL format. 

Could you help me to find a proper way to use counter_culture with dynamic column name?
Is there a way to use scope in `column_names` instead of SQL query?

Regards, Dmytro

**Comment by magnusvk** [comment]
That's the price you pay for being able to fix counts in aggregate—it needs SQL-style conditions. This is all working as designed and documented.

**Comment by MobileD2** [comment]
I found one solution to do that. It could be done by extracting where clause from scope via Arel:

```
counter_culture :order_group,
                  column_name: proc{ |model| model.opened? ? :open_orders_count : nil },
                  column_names: {
                      [Order.opened.arel.ast.cores.last.wheres.last.to_sql] => :open_orders_count
                  }
```

**Comment by magnusvk** [comment]
@MobileD2 that's great! FWIW, I'd be happy to look at a pull request that adds support for using scopes here directly.
