### ISSUE TITLE
Possible to track a total count and two conditional counts?

### ISSUE THREAD

**Issue by Zhao-Andy** [magnusvk/counter_culture#259]
I'm trying to keep track of three columns on a single table/model: `credits_count`, `unspent_credits_count` and `spent_credits_count`. Right now, I've only been able to count either:
- _only_ the total `credits_count`, or
- _both_ the `spent_credits_count` and `unspent_credits_count`.

After looking at the documentation, there isn't a clear example of whether this is possible or not. I'm guessing it is -- happy to make a PR to add documentation for it. However, if it's not, I think the functionality is worth adding.

#### This first example counts _only_ `credits_count`:
```ruby
# user.rb
class User
  has_many :credits
end
# has credits_count, unspent_credits_count and spent_credits_count columns
```
```ruby
# credit.rb
class Credit
  belongs_to :user
  counter_culture :user,
    column_names: {
                    ["credits.spent = ?", true] => "spent_credits_count",
                    ["credits.spent = ?", false] => "unspent_credits_count",
                    ["credits.id > ?", 0] => "credits_count"
                  }
end
```

```ruby
# rails console
user = User.first
user.credits_count
#=> 0
user.unspent_credits_count
#=> 0
3.times { Credit.create(user: user, spent: false) }
2.times { Credit.create(user: user, spent: true) }
user.reload
user.credits_count
#=> 5
user.unspent_credits_count
#=> 0
user.spent_credits_count
#=> 0
Credit.counter_culture_fix_counts
#=>
[
  {:entity=>"User", :id=>11, :what=>"unspent_credits_count", :wrong=>0, :right=>3},
  {:entity=>"User", :id=>11, :what=>"spent_credits_count", :wrong=>0, :right=>2},
]
```

#### This second example counts **both** `unspent_credits_count` and `spent_credits_count` but not `credits_count`:
```ruby
# user.rb
class User
  has_many :credits
end
# has credits_count, unspent_credits_count and spent_credits_count columns
```
```ruby
# credit.rb
class Credit
  belongs_to :user
  counter_culture :user,
    column_name: proc { |model| "#{model.spent ? 'spent' : 'unspent'}_credits_count" },
    column_names: {
                    ["credits.spent = ?", true] => "spent_credits_count",
                    ["credits.spent = ?", false] => "unspent_credits_count",
                    ["credits.id > ?", 0] => "credits_count"
                  }
end
```

```ruby
# rails console
user = User.first
user.credits_count
#=> 0
user.unspent_credits_count
#=> 0
user.spent_credits_count
#=> 0
3.times { Credit.create(user: user, spent: false) }
2.times { Credit.create(user: user, spent: true) }
user.reload
user.reload.credits_count
#=> 0
user.reload.unspent_credits_count
#=> 3
user.reload.spent_credits_count
#=> 2
Credit.counter_culture_fix_counts
#=>
[
  {:entity=>"User", :id=>11, :what=>"credits_count", :wrong=>0, :right=>5},
]

```

**Comment by magnusvk** [comment]
Sorry, but this is not a support hotline. Why don't you give it a try and then report back? I think this should work, but maybe I'm missing something.

**Comment by Zhao-Andy** [comment]
No worries; this is more of a bug report, but could possible be just an issue with configuration. If it is the latter, I'd be more than willing to add some documentation for it. To be clear, both examples are not working as expected, but perhaps I configured it wrong. The TL;DR is that each respective configuration results in some of the columns not being tracked properly. 

The first configuration results in `credits_count` only being tracked. The second configuration results in `spent_credits_count` and `unspent_credits_count` being tracked. Both solutions require `Credit.counter_culture_fix_counts` for their respective non-working columns to match.

The codebase I'm working on currently uses the second configuration because we don't use `credits_count` yet, but it ideally should match properly without the use of `fix_counts`. I've now added some credits to my own user, and unfortunately as expected, `unspent_credits_count` was updated properly and not `credits_count`.

**Comment by ssingh510** [comment]
@Zhao-Andy were you able to find a solution for this? i'm also having this issue

**Comment by magnusvk** [comment]
And just to be clear, if you can open a PR with either a failing test case or even better an improvement to that, I'm more than happy to take a look at that. @ssingh510 not surprised it would generate two queries; not immediately clear to me how much effort it would be to change that.
