### ISSUE TITLE
Syntax for limiting a polymorphic association

### ISSUE THREAD

**Issue by joelcahalan** [magnusvk/counter_culture#269]
I only want to have a count for one model that has_many of a polymorphic association. What is the proper syntax for specifying this in the counter_culture macro?

Thanks!

**Comment by joelcahalan** [comment]
I tried this syntax but it didn't seem to work:
`belongs_to :imageable, polymorphic: true`
 `counter_culture :imageable, only: :product`

**Comment by magnusvk** [comment]
Please check the documentation with questions like these. Issues are not a support hotline.

You could try to use conditional counter caches to achieve this: https://github.com/magnusvk/counter_culture/blob/master/README.md#conditional-counter-cache
