### ISSUE TITLE
Help with conditional

### ISSUE THREAD

**Issue by jepzen** [magnusvk/counter_culture#273]
I have added 3 counters for my model with code

  ```
belongs_to :job
counter_culture :job, column_name: proc {|model| model.status == -2 ? 'pending_count' : nil }
counter_culture :job, column_name: proc {|model| model.status == 1 ? 'signed_up_count' : nil }
counter_culture :job, column_name: proc {|model| model.status == 3 ? 'rejected_count' : nil }
 
```

My tests works fine, the count goes up depeding on the status when i try to run 

Invitation.counter_culture_fix_counts i get this error

`RuntimeError: Must provide :column_names option for relation [:job] when :column_name is a Proc; you may skip this relation with :skip_unsupported => true
`

But when I run with :skip_unsupported => true nothing happens. Have I misunderstood how to use this gem?

**Comment by narze** [comment]
@jepzen You have to add `column_names` as stated in https://github.com/magnusvk/counter_culture#handling-dynamic-column-names to help the gem query and fix the cached counters.

For your case the code should be like this:
```
counter_culture :job, 
                column_name: proc {|model| model.status == -2 ? 'pending_count' : nil }
                column_names: {
                  ["model_table.status = ?", -2] => 'pending_count'
                }
```

**Comment by jepzen** [comment]
Thanks, that made it work
