### ISSUE TITLE
Using with Sidekiq batch jobs

### ISSUE THREAD

**Issue by mrsweaters** [magnusvk/counter_culture#274]
I'm running into an issue where `counter_culture_fix_counts` is not able to complete in a reasonable amount of time, event with smaller `batch_size` settings? Is it possible to make this work with Sidekiq batch jobs, so that my jobs are not long running?

**Comment by magnusvk** [comment]
That's not something that's built into counter_culture. I'd love to see a PR for this though! Or you could probably make this work for yourself using the `where` option to `counter_culture_fix_counts` and thus split up the work across multiple Sidekiq jobs.

**Comment by mrsweaters** [comment]
Thanks @magnusvk, I'll look into it.
