### ISSUE TITLE
Redis storage

### ISSUE THREAD

**Issue by crazyshot** [magnusvk/counter_culture#275]
Hi there.
Is there a plan to add or maybe some already known fork that adds storing the counter cache in Redis?
We have a relation of tag <-> tag_follower with relatively small (100k rows) number of tags and millions of followers that are very rapidly changing, and updating the followers' cache count in the DB created a lot of deadlocks. We decided to offload this counter cache to Redis with sorted set per table:field, but it seems that we'd need to do it manually as opposed to using counter_culture.

**Comment by magnusvk** [comment]
Not planned and no fork I know of. Your use case makes sense, though. 

Honestly, the easiest thing for you to do if you need this for only one table is probably to add some manual callbacks and manage counts that way. 

That being said, if you did come up with a fork that makes counter storage pluggable and that adds a Redis storage option I’d certainly review that.
