### ISSUE TITLE
counter_culture breaks code if any of the attributes is read only

### ISSUE THREAD

**Issue by Morozzzko** [magnusvk/counter_culture#278]
I'm using [aasm](https://github.com/aasm/aasm) on my ActiveRecord model. I've used the `no_direct_assignment: true` option, so any attempts to call `my_model.attr = ...` will fail with an exception.

Once I introduce `counter_culture` to the class, the application breaks – the class will raise an exception if try to update it. 

This behavior should be reproducible even without AASM by overriding the writer, like this

```ruby
def attr=(*)
  raise "Welp"
end
```

**Here's why it happens**: 
1. `CounterCulture::Counter#previous_model` calls `#saved_changes` on my model, and it includes the read-only fields. It probably happens because the model has been created and updated in the same business process / transaction.  
2. It tries to write the attribute to recreate _some old_ state
3. It fails

Here's the problematic spot:

https://github.com/magnusvk/counter_culture/blob/e0e0302c56fb616d2d4cd8e5e93a035099629aeb/lib/counter_culture/counter.rb#L287-L297

Here's an old article on the same problem:

http://natural-hokke.hateblo.jp/entry/2017/12/29/221943

**Comment by magnusvk** [comment]
Thanks for the detailed report—this makes sense. Are you able to open a pull request with a fix? If `aasm` uses the Rails-standard read-only attributes here, we should be able to just say `next if  obj.klass.readonly_attributes.include?(key)`, right? ([See here.](https://api.rubyonrails.org/classes/ActiveRecord/ReadonlyAttributes/ClassMethods.html#method-i-attr_readonly)) However, it will also need a test.

**Comment by Morozzzko** [comment]
I'll need to check it out. I'm not sure it's _that_ kind of read-only.

But it might work, actually. Thanks! 

I'll send a PR if it works out
