### ISSUE TITLE
migration not Rails version aware 

### ISSUE THREAD

**Issue by jasonfb** [magnusvk/counter_culture#280]
the generator creates a migration with the old-style Migration class `ActiveRecord::Migration`

```
Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
```

I think there's a way to pipe the Rails version into the template as it is being generated 

I did it in another gem like this
```
class CreateUniversalTrackManagerTables < ActiveRecord::Migration<%= migration_version %>
  def self.up
    ActiveRecord::Base.transaction do

```

**Comment by magnusvk** [comment]
@jasonfb thanks for reporting this, I believe it's just a bad version check in the generator. Can you verify that #281 fixes this?
