### ISSUE TITLE
Improving the use of column_names and scopes

### ISSUE THREAD

**Issue by maikdijkstra** [magnusvk/counter_culture#289]
As of now the column column_name is always necessary to create a counter. With some things this would result in large pieces of code which could be minimized a lot using only the column_names. Especially when using scopes.

For example:
```ruby
class City < ActiveRecord::Base
  belongs_to :prefecture
  scope :big, -> { where('population > ?', 100000) 
  scope :small, -> { where('population < ?', 10000) }
  scope :small_and_big_cities, -> { where('population > ? OR population < ?', 100000, 10000) }

  counter_culture(
    :prefecture,
    column_name:  ->(model) { model.big? ? :big_cities_count : nil },
    column_names: { 
        City.big => :big_cities_count
    }
  )

counter_culture(
    :prefecture,
    column_name:  ->(model) { model.small? ? :small_cities_count: nil },
    column_names: { 
        City.small => :small_cities_count
    }
  )

  counter_culture(
    :prefecture,
    column_name:  ->(model) { (model.big? || model.small?) ? :small_and_big_cities_count : nil },
    column_names: { City.big => :small_and_big_cities_count }
  )

  def big?
     population > 100000
  end
  def small?
     population < 10000
  end
end
```
This is a small example with just 2 options and a combination of those. But takes quite a lot of lines. I would like to write it like this to easily create more counters without having large pieces code 
```ruby
class City < ActiveRecord::Base
  belongs_to :prefecture
  scope :big, -> { where('population > ?', 100000) }
  scope :small, -> { where('population < ?', 10000) }
  scope :small_and_big_cities, -> { where('population > ? OR population < ?', 100000, 10000) }

  counter_culture(
    :prefecture,
    column_names: { 
      City.big => :big_cities_count,
      City.small => :small_cities_count,
      City.small_and_big_cities => :small_and_big_cities_count
    }
  )
end
```
In this way the column_names is used as a kindof mapping. I have edited the code to handle this situation and I think this would be a very nice addition to this already good gem! Please let me know if you want me to open a PR for this.

**Comment by magnusvk** [comment]
I agree it would be nice to be able to define your column names just once, I just don't know how to get there consistently and while supporting the full functionality of the gem. #290 I don't think gets us there. I'll close this here as I don't know how I'd achieve this, but I'm happy to keep discussing more ideas as I agree it would be nice to have this functionality.
