### ISSUE TITLE
Add explanation about usage of column_names option in README

### ISSUE THREAD

**Issue by litalico-tomokioke** [magnusvk/counter_culture#293]
Hello.

`counter_culture` method has options, `column_name` and `column_names`.
These two option names are so similar,
but I can't find an explanation about difference between them and what for `column_names` in README.

My recognition is that
`column_name` is used for specifying which columns to increment or decrement in source table's record changing,
but `column_names` is used for specifying which columns to update in fixing or initializing by `counter_culture_fix_counts`.

If my above recognition is correct, I propose adding an explanation about what for `column_names` option in README.

**Comment by magnusvk** [comment]
The existing documentation for that is here: https://github.com/magnusvk/counter_culture#handling-dynamic-column-names

Is that section not helpful? Your understanding is correct. Definitely open to improving this, though I'm not quite clear how.

**Comment by magnusvk** [comment]
Fixed by #294 I believe.
