### ISSUE TITLE
column_names option lead to database not exist when run rake db:create

### ISSUE THREAD

**Issue by SmileDMiao** [magnusvk/counter_culture#298]
Rails: 6.0
counter_culture: 2.6.2

I found if i delete the column names option the `rake db:create` command will success. when add it back , run `rake db:create` raise database not exist error.

```ruby
counter_culture :user, column_name: proc { |order| order.checked? ? 'spent_amount' : nil }, delta_column: 'spent', column_names: {
      Prediction::Order.checked => 'spent_amount',
    }
```

**Comment by SmileDMiao** [comment]
change the code
```ruby
 counter_culture :user, column_name: proc { |order| order.checked? ? 'spent_amount' : nil }, delta_column: 'spent', column_names: {
      ["prediction_orders.status = ?", 2] => 'spent_amount',
    }
```
will not raise the error.

**Comment by magnusvk** [comment]
Looking at this, what's probably going on is that `rake` is loading your app on `db:create` which triggers the `Prediction::Order.checked` code which will in turn raise the "database does not exist" error. I'm not really sure how to work around this, to be honest, other than what you've already done here. I'm going to close this as this isn't strictly related to counter_culture, but if you have a good idea on how to work around this I'm happy to discuss it.

**Comment by Archetylator** [comment]
Probably to resolve that issue you can put counter definitions inside this code:

```
if Prediction::Order.table_exists?
...
end
```

**Comment by magnusvk** [comment]
That could work, feel free to open a PR for it and I'm happy to take a look!
