### ISSUE TITLE
Manually filling in dynamic column name based on joined model

### ISSUE THREAD

**Issue by dzoltok** [magnusvk/counter_culture#30]
OK, so I have a situation where an Article has_many Tags, and a Tag has_many Articles, through a join table that belongs_to both of them. That's where this code is:

```
class ArticlesTag < ActiveRecord::Base
  belongs_to :article
  belongs_to :tag

  counter_culture :tag, column_name: "articles_count"
  counter_culture :tag, column_name: Proc.new{ |model| model.article.recent? ? 'recent_articles_count' : nil }
```

As you can see, I'm trying to store both the number of articles associated with a tag, and the number of "recent" articles. The problem here comes up when I try to populate the count columns in the Tag table using counter_culture_fix_counts:

```
Must provide :column_names option for relation [:tag] when :column_name is a Proc; you may skip this relation with :skip_unsupported => true
```

But I can't figure out how to properly configure that option. The condition that makes an article recent is on the article table itself, not the join table where all the counter_cache code is going. If I add an option like:

```
column_names: {
  ["articles.created_at > ?", 30.days.ago] => 'recent_articles_count'
}
```

I just get an error that there is no such column 'articles.created_at', since the articles table isn't being joined in when it tries to run the counter_culture_fix_counts command.

**Comment by swapnilabnave** [comment]
I would like to [contribute](https://github.com/magnusvk/counter_culture#contributing-to-counter_culture) and add an option for `joins`. Would that be a good thought ?
I know it wont be efficient in terms of space and time but it would be an **option** eventually.

```ruby
counter_culture :tag,
   column_name: Proc.new{ |model| model.article.recent? ? 'recent_articles_count' : nil },
   joins: ["articles"],
   column_names: { ["articles.recent = ?", true] => 'recent_articles_count' }
```

**Comment by magnusvk** [comment]
@swapnilabnave I'm not sure I understand how that would work. I'm open to adding some sort of support here going forward, but I'd need some more details to know whether that makes sense.

**Comment by swapnilabnave** [comment]
@magnusvk 
Ok. So here's real case scenario, which I was trying to achieve using [`counter_culture`](https://github.com/magnusvk/counter_culture).

```ruby
class Conversation < ActiveRecord::Base
  attr_accessible :name, :guest_count

  has_many   :conversation_members
  has_many   :guest_users, through: :conversation_members, source: :user, conditions: ["users.user_type = ?", 'G']
end

class ConversationMember < ActiveRecord::Base
  attr_accessible :conversation_id, :user_id

  belongs_to :conversation
  belongs_to :user

  counter_culture :conversation,
  	column_name: proc {|conv_member| conv_member.user.is_guest? ? 'guest_count' : nil },
  	column_names: {
		  ["users.user_type = ?", 'G'] => 'guest_count' ## I need to check the condition on `users` table instead of `conversation_members` table
		}
end
```

I want to count the `guest_users` for each `conversation`, this would require a join of `users` and `conversation_members`. 

So I am basically trying to form a query which looks likes this. It gives me the guest_count as expected.

```sql
SELECT 
    conversations.id,
    COUNT(conversation_members.id) AS count,
    conversations.guest_count
FROM
    `conversations`
        LEFT JOIN
    conversation_members AS conversation_members ON conversations.id = conversation_members.conversation_id
        LEFT JOIN
    users ON users.id = conversation_members.user_id
WHERE
    users.user_type = 'G'
GROUP BY `conversations`.`id`
ORDER BY count DESC
LIMIT 1000;
```

With that said, if I add a `joins` **option** in `counter_culture` method case can be solved.


```ruby
  counter_culture :conversation,
  	column_name: proc {|conv_member| conv_member.user.is_guest? ? 'guest_count' : nil },
  	joins: ['users']
  	column_names: {
		  ["users.user_type = ?", 'G'] => 'guest_count' ## I need to check the condition on `users` table instead of `conversation_members` table
		}
```

> but I'd need some more details to know whether that makes sense

Does that makes sense ? Or am I just over doing it which might not be really necessary ?

--

Btw. I solved the problem without `counter_culture` though, using traditional ActiveRecord#after_save callback.

**Comment by magnusvk** [comment]
Got you, that makes sense. 

I think it's perfectly reasonable to use counter_culture for this with a custom fix_counts method you build, right? You wouldn't need to make all the actual counting work, the gem would do that, you'd just write a single method to fix counts. Seems easier than extending the gem. :)

That being said, if you added something here I'd be happy to look at a pull request.

**Comment by jayehernandez** [comment]
I encountered a similar scenario as @swapab, I was wondering if the joins option is already included in the gem?

**Comment by magnusvk** [comment]
No, unfortunately #138 was abandoned before it was ready to merge.
