### ISSUE TITLE
Rails 6.1 w/ PaperTrail compatibility issues

### ISSUE THREAD

**Issue by swiknaba** [magnusvk/counter_culture#302]
Currently, PaperTrail itself is not yet fully Rails 6.1. compatible.

## paper_trail.save_with_version
In particular, I've found the following method to be broken: `paper_trail.save_with_version(validate: false)`. The issue here is a splat vs. double splat operator in Rails' `ActiveRecord#save` method. I've attempted to fix this in PaperTrail: https://github.com/paper-trail-gem/paper_trail/pull/1284

Just leaving this as a warning here in case you're wondering, why counter culture does not work with Rails 6.1. You can test this by simply checking this repo out, and running the specs using Rails 6.1. This will result in the following error:

```
Failure/Error: instance.paper_trail.save_with_version(validate: false)
     
ArgumentError:
  wrong number of arguments (given 1, expected 0)
```

trace:
```
# ~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.0/lib/active_record/suppressor.rb:43:in `save'
# ~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/paper_trail-11.1.0/lib/paper_trail/record_trail.rb:205:in `block in save_with_version'
# ~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/paper_trail-11.1.0/lib/paper_trail/request.rb:110:in `with'
# ~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/paper_trail-11.1.0/lib/paper_trail.rb:91:in `request'
# ~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/paper_trail-11.1.0/lib/paper_trail/record_trail.rb:204:in `save_with_version'
# ./lib/counter_culture/counter.rb:96:in `change_counter_cache'
# ./lib/counter_culture/extensions.rb:97:in `block in _update_counts_after_create'
# ./lib/counter_culture/extensions.rb:95:in `each'
# ./lib/counter_culture/extensions.rb:95:in `_update_counts_after_create'
```

Unsure, if we need to restrict the dependencies as follows:
```
spec.add_development_dependency 'rails', '>= 4.2', '< 6.1'
```
🤷

**Comment by magnusvk** [comment]
@swiknaba thanks for the report. I can skip testing PaperTrail for Rails 6.1 for now to make sure the rest of the project works. See #303 for progress on that. I subscribed to the PaperTrail issue you linked so hopefully I can enable tests for Rails 6.1 as soon as PaperTrail fixed that issue. That being said, still working on testing Ruby 3 and Rails 6.1! :)
