### ISSUE TITLE
`counter_culture_fix_counts` doesn't work with `column_name` and `where` together

### ISSUE THREAD

**Issue by dvandersluis** [magnusvk/counter_culture#305]
I have the following model relationship:

```ruby
class User < ApplicationRecord
end

class Group < ApplicationRecord
  has_many :group_owners
  has_many :users, through: :group_owners
end

class GroupOwner < ApplicationRecord
  belongs_to :user
  belongs_to :group

  counter_culture :user,
    column_name: ->(model) { model.group.visible? ? 'visible_groups_count' : nil },
    column_names: {
      GroupOwner.visible => :visible_groups_count
    }
end
```

I added a counter cache to `users` that uses counter_culture to count records, based on a field on `groups`. Since it's a has many through, where the `GroupOwner` record is not notified when the `Group` is updated, I need to manually trigger an update of the counter culture when the column changes.

```ruby
class Group < ApplicationRecord
  after_save do
    if saved_change_to_visible?
      GroupOwner.counter_culture_fix_counts(
        only: :user,
        where: { users: { id: user_ids } }
      )
    end
  end
end
```

This works, but I wanted to make it more specific using `column_name` to ensure only the correct column is updated, however neither of these change any data:

```ruby
GroupOwner.counter_culture_fix_counts(
  only: :user,
  column_name: :visible_groups_count,
  where: { users: { id: user_ids } }
)
```

```ruby
GroupOwner.counter_culture_fix_counts(
  column_name: :visible_groups_count,
  where: { users: { id: user_ids } }
)
```

(Side question: is there a better way I could acheive what I'm trying to do here?)

**Comment by magnusvk** [comment]
Sorry, but I don’t understand the issue you are having based off the information you have provided here and I am unable to provide support on this open source project. 

Just to confirm, though, the call to counter_culture is on the GroupOwner model? At first glance here, and again I don’t have enough information, you shouldn’t have to manually update the counter cache. This seems like a pretty straightforward case.
