### ISSUE TITLE
Conditional count on transitive relationship

### ISSUE THREAD

**Issue by Amnesthesia** [magnusvk/counter_culture#308]
Let's say I have these kind of models:

```
# integer revision
# integer state
class DocumentRevision < ActiveRecord::Base
  belongs_to :document
  enum state: [:active, :inactive, :deleted]

  counter_culture :class_type,
                  column_name: proc { |document_revision|
                    # Only count active/inactive documents if not counted
                    # before for this document
                    previous_count = document_revision.document.document_revisions.where(state: document_revision.state).count
                    if DocumentRevision.where(document: document_revision.document, state: document_revision.state).count <= 1
                      "#{document_revision.state}_count"
                    end
                  }
end

class Document < ActiveRecord::Base
  belongs_to :category
  has_many :document_revisions
  has_one :latest, class_name: "DocumentRevision"
end

class Category < ActiveRecord::Base
  has_many :products
end
```

What I want to do is have a count of active documents on Category, and a count of inactive documents as well. A document could have DocumentRevisions where all of them are inactive, in which case I dont want that to count. It doesnt seem like my column_name proc works here. A document should be counted as active (+1) if it has at least one active DocumentRevision, and not be counted if it doesn't have any.

**Comment by magnusvk** [comment]
Sorry—but this doesn't look like an issue with the gem and I unfortunately cannot provide support here.

**Comment by Amnesthesia** [comment]
It's not really an issue with the gem except the fact that if I add in a "puts" statement I can see that its being run, but nothing is actually counted. I end up with 0 counts even if I print "WILL COUNT THIS RECORD" and return a string for the column
