### ISSUE TITLE
expire cache manually when a counter is updated

### ISSUE THREAD

**Issue by khiav223577** [magnusvk/counter_culture#317]
I find the gem uses `update_all` to update the counter.
https://github.com/magnusvk/counter_culture/blob/dcdf9cb6e9919b8c287f5ea78531dea2a27d8eac/lib/counter_culture/counter.rb#L116

 It doesn't trigger `after_commit` and causes some cache problem in our project.
Is there a way to expire cache manually?

**Comment by magnusvk** [comment]
This isn’t a support hotline, please read the documentation. It seems you might be looking for the `touch` option. This is all well-documented, though.

**Comment by khiav223577** [comment]
@magnusvk you may misunderstood my problem. In our project, we cache attributes of model in `redis` or `memcached`.
When an counter cache column gets updated, it does not trigger callback to clean the cache. I wonder how do others deal with this problem?

Take `identity_cache` for example:
```rb
Category.find(1).products_count
# => 2

Category.fetch(1).products_count
# => 2
```
```rb
Product.create(...)

Category.find(1).products_count
# => 3

Category.fetch(1).products_count
# => 2
# expected it to be 3, though.
```

I created an executable test case:
```rb
begin
  require 'bundler/inline'
rescue LoadError => e
  warn 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', '~> 5.2'
  gem 'counter_culture', '~> 2.8'
  gem 'identity_cache', '1.1'
  gem 'sqlite3', '1.4.2'
end

require 'rails'
require 'minitest/autorun'
require 'logger'

Rails.cache = ActiveSupport::Cache::MemoryStore.new(expires_in: 5.minutes)

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
IdentityCache.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table 'products', force: :cascade do |t|
    t.string :name
    t.references :category
  end

  create_table 'categories', force: :cascade do |t|
    t.string :name
    t.integer :products_count

    t.index :name, unique: true
  end
end

class Product < ActiveRecord::Base
  belongs_to :category
  counter_culture :category, touch: true
end

class Category < ActiveRecord::Base
  include IdentityCache
  cache_index :name, unique: true

  has_many :products
end

class BugTest < Minitest::Test
  def setup
    Category.create(name: 'A').products.create([{ name: 'Product A1' }, { name: 'Product A2' }])
    Category.create(name: 'B').products.create([{ name: 'Product B1' }, { name: 'Product B2' }])
  end

  def teardown
    Category.delete_all
    Product.delete_all
  end

  def test_counter_culture
    assert_equal 2, Category.find_by(name: 'A').products_count

    Category.find_by(name: 'A').products.create(name: 'Product A3')
    assert_equal 3, Category.find_by(name: 'A').products_count
  end

  def test_counter_culture_with_identity_cache
    assert_equal 2, Category.fetch_by_name('A').products_count

    Category.find_by(name: 'A').products.create(name: 'Product A3')
    assert_equal 3, Category.fetch_by_name('A').products_count
  end
end
```

**Comment by magnusvk** [comment]
Ok, so yes—setting `touch: true` still uses `update_all` and won’t trigger callbacks. Obviously there’s performance benefits to that but it comes with tradeoffs. It _does_ update the timestamp, so you could use a `Rails.cache.fetch` block that incorporates the timestamp as a cache key. That way the cache would automatically get regenerated when that timestamp changes. But it looks like that’s a pretty big departure from your current caching strategy.

If you wanted to work on a PR that adds saving with callbacks as an optional behavior, I’d certainly be open to look at that but it’s not something I will work on myself.
