### ISSUE TITLE
counter_culture_fix_counts returning an empty array. 

### ISSUE THREAD

**Issue by 14ypark** [magnusvk/counter_culture#321]
![Screen Shot 2021-05-12 at 4 33 47 PM](https://user-images.githubusercontent.com/9920555/118040656-d56e0180-b33f-11eb-8cf4-3a902d67f089.png)

No errors or anything it just returns an empty array.

**Comment by magnusvk** [comment]
Please check the Readme, this is not a support hotline. Also, you are including zero information here making it impossible to help you even if I wanted to.

**Comment by 14ypark** [comment]
No errors or anything it just returns an empty array.

**Comment by 14ypark** [comment]
@magnusvk please take a look. Thanks
