### ISSUE TITLE
Counter is not updated when it is used in rspec

### ISSUE THREAD

**Issue by 14ypark** [magnusvk/counter_culture#323]
When I write a test case in rspec to test if the counter works correctly, the counter is not updated correctly.

**Comment by magnusvk** [comment]
You are including zero helpful information here, so I can't even help you debug what is wrong. This gem has plenty of rspec tests and is used in lots of projects in production, so I'm quite sure it works. If you find an error that is not covered, feel free to open a PR with a failing test and I will take a look.
