### ISSUE TITLE
Is there any support for many-to-many conditional counter?

### ISSUE THREAD

**Issue by lilisako** [magnusvk/counter_culture#328]
## Question
Hi, I'm using this gem for a while, and I'd like to ask about a many-to-many association.  My models are something like below. 
```
class Actor 
  has_many :films, through: :actor_films

  name: string
  film_count: integer 
```
```
class Film
  has_many :notes, through: :actor_films

  available: boolean
  name: string
```
```
class ActorFilm
  belongs_to :Film 
  belongs_to :Actor
```
## What I want to do 
Now, I need to get a film_count of each actor which is available. And you need to define `counter_culture` in `models/actor_file.rb`.
Intuitively what I want to do is this below. 
```
class ActorFilm < ApplicationRecord
   counter_culture :actor, column_name: proc { |model| model.film.available? ? 'film_count' : nil }
```

I really appreciate any help you can provide.

**Comment by lilisako** [comment]
I'm closing this issue since I found a solution here. 
https://github.com/magnusvk/counter_culture#many-to-many-association  
I'm sorry for making this issue, and I appreciate all the work the author has done.🙏

**Comment by lilisako** [comment]
Misunderstanding was here, what I wanted to do here is **many-to-many conditional counter**, which hasn't documented in readme. My apology to make things complicated. I'm editing the issue title.

**Comment by magnusvk** [comment]
That should work I believe. Did you try it before opening the issue?
