### ISSUE TITLE
How to decrement count when an attribute value changes?

### ISSUE THREAD

**Issue by Infi-Knight** [magnusvk/counter_culture#349]
Hi, is it possible to decrement the count when I update an attribute's value e.g set it to `false`? The thing is that I have configured my model in such a way that instead of deleting the record I am simply archiving it using a custom boolean attribute named `archive`. The count is incremented properly when an item is added but not when it is archived (probably because no destroy callback is run?).  Here is the schema:

```
class Pod < ApplicationRecord
  belongs_to :project
  belongs_to :team, optional: true
  counter_culture :project
```

```
class Project < ApplicationRecord
  has_many :pods
```

```
class Team < ApplicationRecord
  has_many :pods
  has_many :projects
```

I would be grateful for any advice on solving this use case. Thank you  🙇

**Comment by seyerian** [comment]
@Infi-Knight See the `:column_name` option; this allows you introduce logic via a proc. https://github.com/magnusvk/counter_culture#conditional-counter-cache

So something like:

```ruby
class Pod < ApplicationRecord
  belongs_to :project
  belongs_to :team, optional: true
  counter_culture :project, column_name: proc { |pod| !pod.archived? ? 'pods_count' : nil }
end
```
