### ISSUE TITLE
Multiple counters, single query

### ISSUE THREAD

**Issue by thimmaiah** [magnusvk/counter_culture#354]
Is it possible to generate a single query and update the counters ? I have many counters and the number of queries is piling up.

Thanks in advance

**Comment by Singh212dab** [comment]
yes but not possible to mix counter query and non counter query in cassandra.

**Comment by thimmaiah** [comment]
How to accomplish this, for mysql like DBs? Currently I have 10 counters which generate 10 different queries.

**Comment by Singh212dab** [comment]
sorry mate no idea about it ,you can go for Google . only thing I know that it is possible

**Comment by magnusvk** [comment]
This isn't currently possible. If you wanted to open a PR that adds this functionality I'd be happy to look at it.

**Comment by marinfr** [comment]
https://github.com/magnusvk/counter_culture/pull/393
