### ISSUE TITLE
Multi-level association 3-deep works in the console, but fails every test and in production

### ISSUE THREAD

**Issue by kkerley** [magnusvk/counter_culture#360]
This is so weird. I have a very complex and deeply-relational site that tracks live music performances, the songs played, any (un)official recordings that exist, and more. I'm attempting to add a counter-cache for the number of recordings that exist for performances a song was played at.

 I've been trying all different approaches to listing out the models in an array as shown in the documentation for multi-level counter-caches. No matter what, all my specs fail. I decided to try `counter_culture_fix_counts` at the command line and just see if anything was working. Weirdly enough, the following iteration is the only one that not only doesn't throw an error, but correctly updates the desired counter-cache column on each Song record:

`counter_culture [:performance, :played_songs, :song], column_name: 'recordings_count'`
(the column_name is likely unnecessary, but I specified it to be totally sure)

```
Recording.counter_culture_fix_counts
  Microphone Load (1.7ms)  SELECT "microphones".id, "microphones".id, COUNT("recordings".id)*1 AS count, MAX("microphones".recordings_count) AS recordings_count FROM "microphones" LEFT JOIN "recordings" AS recordings ON "microphones".id = recordings.microphone_id GROUP BY "microphones"."id" ORDER BY "microphones"."id" ASC LIMIT $1  [["LIMIT", 1000]]
  Song Load (16.8ms)  SELECT "songs".id, "songs".id, COUNT("recordings".id)*1 AS count, MAX("songs".recordings_count) AS recordings_count FROM "songs" LEFT JOIN "played_songs" AS played_songs ON "songs".id = played_songs.song_id LEFT JOIN "performances" AS performances ON "played_songs".performance_id = performances.id LEFT JOIN "recordings" AS recordings ON "performances".id = recordings.performance_id GROUP BY "songs"."id" ORDER BY "songs"."id" ASC LIMIT $1  [["LIMIT", 1000]]
  TRANSACTION (0.2ms)  BEGIN
  Song Update All (5.9ms)  UPDATE "songs" SET recordings_count = 306 WHERE "songs"."id" = $1  [["id", 1]]
  Song Update All (0.3ms)  UPDATE "songs" SET recordings_count = 659 WHERE "songs"."id" = $1  [["id", 2]]
  Song Update All (0.3ms)  UPDATE "songs" SET recordings_count = 190 WHERE "songs"."id" = $1  [["id", 3]]
  Song Update All (0.2ms)  UPDATE "songs" SET recordings_count = 1421 WHERE "songs"."id" = $1  [["id", 4]]
...
and etc
```
Above shows the start of the output received and it continues for quite a ways. I spot checked a number of songs via Postman and in the console and everything matched when I checked `song.recordings.count` against the `song.recordings_count` counter_culture counter-cache column. 

It was perfect and did exactly what I wanted, which was awesome after a number of frustrating hours with endlessly failing specs. 

...and despite the fact it works exactly how it should using the `Recording.counter_culture_fix_counts` method in the Rails console, specs always fail. It's the same NoMethodError in each of the corresponding failing specs:

```
Failure/Error: let!(:recording1) { create(:recording, performance_id: performance1.id, microphone_id: microphone.id, taper_id: taper.id) }
      
      NoMethodError:
        undefined method `song' for #<ActiveRecord::Associations::CollectionProxy []>
```

When I try to create a new Recording record in the dev site, using the front end to feed to the API, I get:

``` NoMethodError (undefined method `song' for #<PlayedSong::ActiveRecord_Associations_CollectionProxy:0x00007f37802af530>):```

If I comment out the counter_culture line from above, everything passes and works fine, but the counter-cache isn't functional then obviously, and I'm back to calling `@song.recordings.count` in my controller responses. 

The most relevant information about the models that are part of the situation:

**performance.rb**
```
has_many :played_songs, dependent: :destroy
has_many :songs, through: :played_songs
has_many :recordings
```

**played_song.rb**
```
belongs_to :performance
belongs_to :song

counter_culture :performance
counter_culture :song
```

**recording.rb**
```
belongs_to :performance

# Plural ':played_songs' works with Recording.counter_culture_fix_counts, but still fails specs
counter_culture [:performance, :played_songs, :song], column_name: 'recordings_count' 
counter_culture [:performance]
```

**song.rb**
```
has_many :played_songs, dependent: :destroy
has_many :performances, through: :played_songs
has_many :recordings, through: :performances
```

The documentation examples only show simple multi-leveling, and only two total levels. Nothing is explicitly mentioned that I saw, but does this not officially work deeper than two levels? Or is it because it's deep AND there's a has_many through: association involved (CollectionProxy issue)? 

It's so unbelievably weird that it this works perfectly via `Recording.counter_culture_fix_counts` at the command line, but is completely broken when it comes to the site functioning and specs passing. 

Is there some obvious Ruby/Rails convention I'm totally blanking on?

I've tried making that line:
`counter_culture [:performance, :played_song, :song], column_name: 'recordings_count' `
`counter_culture [:performance, :played_song], column_name: 'recordings_count' `
`counter_culture [:performance, :song], column_name: 'recordings_count' `

And the error from both the spec and `counter_culture_fix_counts` output is always along the lines of no such association or column existing.

**Comment by magnusvk** [comment]
This should work for more than two levels, [there's even a spec that tests three levels](https://github.com/magnusvk/counter_culture/blob/82abf9c2fc1a29898999d4af8b2611000710a537/spec/models/review.rb#L16). Looking at yoru code, my hunch is that the issue is you're trying to go through a `has_many` association when updating the counter cache. You're going recording -> performance -> played_songs—and I think maybe that doesn't work? In the test I linked above it goes just through `belongs_to` associations.
