### ISSUE TITLE
counter_culture_fix_counts with where clause

### ISSUE THREAD

**Issue by thimmaiah** [magnusvk/counter_culture#361]
Is it possible to call counter_culture_fix_counts with a where clause.
So I have a situation where 
1. I do bulk import of records using active record imports for one specific client. 
2. This of course does not update the counters. 
3. So post the import I want to run counter_culture_fix_counts. 

However this runs the fix across the entire table, ideally I would want to fix the counters only for a specific client. Is this possible ?
Ex Payment.where(client_id: 1234).counter_culture_fix_counts

**Comment by magnusvk** [comment]
[Yeah, see the last example in the documentation here.](https://github.com/magnusvk/counter_culture#manually-populating-counter-cache-values)

**Comment by thimmaiah** [comment]
Thanks this works, appreicate it

**Comment by Nechitadi** [comment]
is this still working?
