### ISSUE TITLE
what is the drawback of using active records callback instead this gem?

### ISSUE THREAD

**Issue by laptopmutia** [magnusvk/counter_culture#366]
hello for the dear creator of this game pardon my language if it bothers you

I'm junior rails programmer and one of my mentor tell me to use this gem so I use this gem, this gem is really good for my project.

I use this app to sum a total of children model's total that is saved on a parent model
my models are like this 

```ruby
class Bill < ApplicationRecord
  has_many :bill_entries, dependent: :destroy, inverse_of: :bill
  has_one :journal, as: :journalable
end
```

```ruby
class BillEntry < ApplicationRecord
  belongs_to :bill
  counter_culture :bill, column_name: "total", delta_column: "amount"
  counter_culture :bill, column_name: "vat_total", delta_column: "vat_amount"
  counter_culture :bill, column_name: "grand_total", delta_column: "grand_amount"
```

it works flawlessly and have no mistake, also it have correction function that sometimes I run to fix a miss calculation that happens 
usually it happens because my app update many children all at once (without wrapping it in transaction blocks) thus the miss calculations happening, since I wrap my code with transaction blocks I got no ticket or phone call that said there is a miss calculation, splendid!

now the app that I make is growing and I met a problem where I need to update another child of my model that have denormalize value

now my bill model have 2 kind of children `journal` and `bill_entries` and I need to keep my bill grand total same as total in journal's child total as per this issue its impossible to do with this gem [350](https://github.com/magnusvk/counter_culture/issues/350)

now after learning about my technical problem apparently I could do what this gem do using actives record callbacks

but I wonder what is the drawbacks or caveats to roll my own implementation using active records callbacks instead using this gem

**Comment by magnusvk** [comment]
[I actually think you might be able to use `delta_magnitude` to accomplish what you're talking about here](https://github.com/magnusvk/counter_culture#delta-magnitude), though I don't have enough detail here to know for sure.

`counter_culture` uses ActiveRecrod callbacks under the hood, so you could certainly reimplement it yourself. But why do that if you don't have to expend the extra effort?
