### ISSUE TITLE
Unnecessary UPDATE query when using delta_column with a default value of 0

### ISSUE THREAD

**Issue by benjaminwols** [magnusvk/counter_culture#392]
When using a delta_column to total the values of children, an unnecessary query is perform on every child creation when the default value is 0.

```
Review Update All (1.7ms)  UPDATE "reviews" SET "review_approvals_count" = COALESCE("review_approvals_count", 0) + 0 WHERE "reviews"."id" = 1
```

Would you be open to a PR that changes https://github.com/magnusvk/counter_culture/blob/af30dc4b9172e219f714bd1c0fcd00a3e05858e3/lib/counter_culture/counter.rb#L53C9-L57C30, to return early if the delta_magnitude is equal to 0?

**Comment by magnusvk** [comment]
Yeah, would love a PR for that.
