### ISSUE TITLE
Counter on polymorphic relationship

### ISSUE THREAD

**Issue by jasajona** [magnusvk/counter_culture#4]
How to make counter on polymorphic relationship?

**Comment by dmitry** [comment]
@deniskorobicyn thanks for the anti-pattern link. There are lot of useful information.

**Comment by vishaldeepak** [comment]
any updates on this, would love to have polymorphic capability, as i have used this extensively in my project.

**Comment by magnusvk** [comment]
Nothing new from my end, unfortunately.

**Comment by danielbonnell** [comment]
Hi,

Are there any updates on this yet or newer forks with this capability? I used this gem extensively in a project and now need polymorphic support. Thanks!

**Comment by magnusvk** [comment]
No unfortunately not.

**Comment by timdiggins** [comment]
#154 is a new(ish) PR for *single-level* polymorphic counters (I think multi-level may be possible, I just haven't come up with a reasonable test case yet).

After a bit of too-ing and fro-ing I think this is working.

If anyone has a use-case for multi-level polymorphic counters can you add a simplified example here -- it would help motivate a subsequent multi-level polymorphic counter PR.

**Comment by magnusvk** [comment]
Closing this as one-level polymorphic relationships are supported now as of version 1.5.0. Thank you @timdiggins for making this happen.
