### ISSUE TITLE
Mongoid support?

### ISSUE THREAD

**Issue by josal** [magnusvk/counter_culture#80]
It seems counter_culture is not supporting mongo as I'm getting this error

```
after_commit_action-0.1.3/lib/after_commit_action.rb:44:in `<module:AfterCommitAction>': uninitialized constant ActiveRecord (NameError)
```

Any plans to support it?
Thanks.

**Comment by dmitrypol** [comment]
bummer, it's a really nice gem.  Wish I could use it but I understand
