### ISSUE TITLE
touch option is not working

### ISSUE THREAD

**Issue by sufleR** [magnusvk/counter_culture#82]
I'm using latest version of gem.

having:

```RUBY
    belongs_to :item
    counter_culture :item, touch: true
```
updates only count. it doesn't change ```updated_at``` column.

log:

```RUBY
  (0.2ms)  BEGIN
  SQL (0.3ms)  INSERT INTO "clicks" ("app_id", "created_at", "item_id", "uuid") VALUES ($1, $2, $3, $4) RETURNING "id"  [["app_id", 2], ["created_at", "2014-11-13 12:07:46.284731"], ["item_id", "54537c274d6163086cc90000"], ["uuid", "54f75b13-5888-416d-b5fc-cac16d10d2e8"]]
  Item Load (0.4ms)  SELECT  "items".* FROM "items"  WHERE "items"."uid" = $1 LIMIT 1  [["uid", "54537c274d6163086cc90000"]]
   (1.5ms)  COMMIT
  SQL (0.9ms)  UPDATE "items" SET "clicks_count" = COALESCE("clicks_count", 0) + 1 WHERE "items"."uid" = '54537c274d6163086cc90000'
```

items table:

```RUBY
  create_table "items", id: false, force: true do |t|
    t.string   "uid",                            null: false
    t.datetime "created_at",                     null: false
    t.datetime "deleted_at"
    t.integer  "clicks_count",       default: 0, null: false
    t.datetime "updated_at"
    t.integer  "app_id",                         null: false
  end
```

**Comment by magnusvk** [comment]
Any chance you could provide a failing test case as a pull request?

**Comment by AlexVPopov** [comment]
I am also having an issue, but unfortunately this is not happening on an open-source project, so I cannot provide a repo.

**Comment by magnusvk** [comment]
There's a test for this [here](https://github.com/magnusvk/counter_culture/blob/master/spec/counter_culture_spec.rb#L1294). Rather than providing the project that has the issue, could you look at expanding that test or adding another test there that fails and shows the issue?

Pending a reproducible test case, going to close this issue.

**Comment by AlexVPopov** [comment]
@magnusvk one question - does `touch: true` also trigger the `after_touch`
callback?

**Comment by magnusvk** [comment]
I don't believe it does.
