### ISSUE TITLE
rails dependency

### ISSUE THREAD

**Issue by sufleR** [magnusvk/counter_culture#83]
Do you need whole rails as dependency?

I'm considering using counter_culture together with rails-api.

**Comment by dmitry** [comment]
Looks like only the activerecord required for this gem: https://github.com/magnusvk/counter_culture/blob/master/counter_culture.gemspec#L119

**Comment by sufleR** [comment]
it was changed after I created this issue
https://github.com/magnusvk/counter_culture/commit/a3fed1ca91148d10e55728021d5e918f770d7bf5
Thank you for noticing.

Issue can be closed
