### ISSUE TITLE
Transactional callback deprecation warning

### ISSUE THREAD

**Issue by wooly** [magnusvk/counter_culture#87]
Hi there,

Since upgrading to 4.2.0.rc1, I've started getting this error

```shell
DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks.
```

When I start the console or run my test suite. I've got the `config.active_record.raise_in_transactional_callbacks = true` line in my application.rb as the rest of the warning suggests, but it makes no difference.

If I remove counter_culture from the Gemfile and re-run the suite, the warnings disappear. Any ideas?

Thanks!

**Comment by magnusvk** [comment]
@wooly @s01ipsist I've merged after_commit_action#2. Can you verify this is now resolved and doesn't happen anymore? Thanks.

**Comment by s01ipsist** [comment]
In my Rails config/application.rb file I had put
`ActiveRecord::Base.raise_in_transactional_callbacks = true`
right below
`require 'rails/all'`
to prevent that warning.

I haven't chased down what's changed since but removing that, and keeping the old counter_culture and after_commit_action gems, no longer displays the warning.
Updating the gems doesn't bring it back so I'm happy it's resolved... Sorry I couldn't be more help.

**Comment by magnusvk** [comment]
That's great to hear, thanks.

**Comment by bbiglari** [comment]
I have this problem with sinatra application. What I should do about it

DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks.

You can opt into the new behavior and remove this warning by setting:

  config.active_record.raise_in_transactional_callbacks = true

 (called from <class:Beverage> at /Users/bbiglari/Projects/moreontap/api/models/beverage.rb:24)
DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks.

You can opt into the new behavior and remove this warning by setting:

  config.active_record.raise_in_transactional_callbacks = true

 (called from <class:CsvUpload> at /Users/bbiglari/Projects/moreontap/api/models/csv_upload.rb:13)
DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks.

You can opt into the new behavior and remove this warning by setting:

  config.active_record.raise_in_transactional_callbacks = true

 (called from <class:CsvUpload> at /Users/bbiglari/Projects/moreontap/api/models/csv_upload.rb:15)
DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks.

You can opt into the new behavior and remove this warning by setting:

  config.active_record.raise_in_transactional_callbacks = true

 (called from <class:Event> at /Users/bbiglari/Projects/moreontap/api/models/event.rb:8)
DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks.

You can opt into the new behavior and remove this warning by setting:

  config.active_record.raise_in_transactional_callbacks = true

 (called from <class:LegacyStaffPick> at /Users/bbiglari/Projects/moreontap/api/models/legacy_staff_pick.rb:10)
DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks.

You can opt into the new behavior and remove this warning by setting:

  config.active_record.raise_in_transactional_callbacks = true

 (called from <class:Store> at /Users/bbiglari/Projects/moreontap/api/models/store.rb:23)
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -I/Library/Ruby/Gems/2.0.0/gems/rspec-support-3.4.1/lib:/Library/Ruby/Gems/2.0.0/gems/rspec-core-3.4.1/lib /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.4.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

**Comment by bbiglari** [comment]
I already have this in my application.rb file, but doesn't work for me.

**Comment by magnusvk** [comment]
If you look at the after_commit_action PR referenced in this issue, you can see that solution only targets Rails apps. If you are in a Sinatra app, perhaps that doesn't work for you? I don't use this in any Sinatra apps though so I'm not sure.

**Comment by bbiglari** [comment]
What is your  Sinatra version ? 
Do you have this issue as well?

**Comment by bbiglari** [comment]
Can you please provide me a solution for Sinatra app?

Thanks

**Comment by magnusvk** [comment]
I only use this with Rails, not Sinatra, so I'm afraid I can't help with this. However I would be happy to merge a pull request that addresses this if you were to make one.

**Comment by bbiglari** [comment]
The source for the warning is  "has_attached_file" from paperclip, which calls " HasAttachedFile.define_on(self, name, options)" on paperclip.rb -> "add_active_record_callbacks" from initialize method, which calls these three 

       @klass.send(:after_save) { send(name).send(:save) }
      @klass.send(:before_destroy) { send(name).send(:queue_all_for_delete) }
      @klass.send(:after_commit, :on => :destroy) { send(name).send(:flush_deletes) }
However, I don't know why the last line cause the issue, since I couldn't track this down to active record.

Any idea?
