### ISSUE TITLE
Custom column name and decrement

### ISSUE THREAD

**Issue by krim** [magnusvk/counter_culture#95]
Hello. I have problem with decrement counter value.
I have review for companies with statuses: moderate, active, disabled.
For default review has status 'moderate', after i change status to 'active' counter cache +1
Code:
counter_culture :company, column_name: Proc.new {|model| model.status == 'active' ? 'reviews_count' : nil }

After that i change status to 'disabled' i my counter cache didn't dectment, which is logical. How i can user counter_culture for decrement counter_cache when i change review status to 'moderated' or 'disabled' from 'active'?

**Comment by magnusvk** [comment]
Actually, that should have worked. I have specs in place that test for this, so I doubt there's a specific bug here. If so, I'd need a failing test that shows this for me to dig further on it.

Are you perhaps updating the column without callbacks? Then counter_culture can't work.

**Comment by krim** [comment]
Excuse me, my fault
