### ISSUE TITLE
Manually populating counts doesn't work with Conditional counter cache

### ISSUE THREAD

**Issue by nbhartiya** [magnusvk/counter_culture#96]
Manually populating counts (https://github.com/magnusvk/counter_culture#manually-populating-counter-cache-values) with Conditional Counter Cache (https://github.com/magnusvk/counter_culture#conditional-counter-cache) leads to error: 

RuntimeError: Must provide :column_names option for relation [:category] when :column_name is a Proc; you may skip this relation with :skip_unsupported => true

How should I get around this and actually manually populate counts for my conditional counter cache?

**Comment by magnusvk** [comment]
This is well-documented behavior; please read the documentation before filing issues.
https://github.com/magnusvk/counter_culture/#handling-dynamic-column-names

**Comment by magnusvk** [comment]
@bartoszkopinski this is an open-source project, you know. Feel free to open a PR to improve the documentation or the behavior itself. I'd be excited to look at it.

Also, frankly, people with your kind of attitude ^^ sometimes make me wonder why I give my time away for free here. So if you don't like my project, feel free to go away.

**Comment by bartoszkopinski** [comment]
@magnusvk You were the one with the attitude criticising OP for not reading docs while the docs are literally wrong and incomplete. 
Same [here](https://github.com/magnusvk/counter_culture/issues/118) and [here](https://github.com/magnusvk/counter_culture/issues/130).

**Comment by magnusvk** [comment]
¯\_(ツ)_/¯

I tried to write docs that explain this, to the best of my ability. If you have a better suggestion, stop complaining and open a PR. That is literally how open source works.
