### ISSUE TITLE
counter_culture_fix_counts report all items all time

### ISSUE THREAD

**Issue by gmgp** [magnusvk/counter_culture#97]
Gemfile.lock  ```counter_culture (0.1.30)```
If i run the counter_culture_fix_counts the report include all items

```ruby
class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
  counter_culture :post
end
```
whit this schema.rb
```ruby
create_table "posts", :force => true do |t|
  ...
  t.integer  "comments_count",        :default => 0, :null => false
  ...
end

```
when i run ``` Comment.counter_culture_fix_counts only: :post```
the report include all items all times
```ruby
[16] pry(main)> Comment.counter_culture_fix_counts only: :post
 ...
{:entity=>"Post",
 :id=>12375,
 :what=>"comments_count",
 :wrong=>1,
 :right=>"1"},
...
```
if I binding with pry in https://github.com/magnusvk/counter_culture/blob/master/lib/counter_culture.rb#L134
```ruby
  model.attributes
=> {"id"=>1, "count"=>"1", "comments_count"=>1}

```

**Comment by magnusvk** [comment]
That's strange. I've [added a spec for this](https://github.com/magnusvk/counter_culture/blob/master/spec/counter_culture_spec.rb#L852) and it's green. What database are you using? Basically, what this tells me is that the SQL `COUNT()` function is returning a string, which is wrong.

**Comment by gmgp** [comment]
yes, it's strange
I have an old app with
```
rails 3.2.11
pg 0.17.0
```
I'm updating :-/
trying to build a bugged working sample, I realized that by updating the gems the problem does not occur

**Comment by magnusvk** [comment]
Ok, so I'll go ahead and close this then. Thanks for reporting back and good luck fixing this.
