### ISSUE TITLE
Counter not updating with touch callbacks

### ISSUE THREAD

**Issue by losadaem** [magnusvk/counter_culture#99]
I'm using dynamic counter column depending on an association value. I'm trying to use touch but this only executes after_touch callbacks and counter_culture only checks after_update callbacks. Could be possible to improve this in the gem so touch also executes the counter checks ?

Thanks

**Comment by magnusvk** [comment]
I'm not sure what you mean; does the dynamic counter column check the update_at column? Otherwise I don't see why you'd need this. In any case, I don't have any plans to add this myself, though I do think it would be possible.
